### ISSUE TITLE
react-aad-implicitflow - Something went wrong

### ISSUE THREAD

**Issue by sheiknaveed** [pnp/sp-dev-fx-webparts#1155]
Dear team,
I was able to create package and when I use gulp serve, am getting the error on webpage "This site can’t provide a secure connection" . If I upload the packahe to my tenant and use the webpart, am getting below error.

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "ab186a1f-8553-41ae-879f-3fe50d6488f7" (UpcomingMeetingsWebPart). Original error: ***Failed to load URL '/react-aad-implicitflow-upcomingmeetingsstrings_en-us_4194498f3428899d89ebf98485bbd02f.js' for resource 'upcomingMeetingsStrings' in component 'ab186a1f-8553-41ae-879f-3fe50d6488f7' (UpcomingMeetingsWebPart). The file was not found in the server.

***INNERERROR:
***Failed to load URL '/react-aad-implicitflow-upcomingmeetingsstrings_en-us_4194498f3428899d89ebf98485bbd02f.js' for resource 'upcomingMeetingsStrings' in component 'ab186a1f-8553-41ae-879f-3fe50d6488f7' (UpcomingMeetingsWebPart). The file was not found in the server.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:4:53239)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:20:104499)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:20:114461)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:20:110492)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_4cb1a85562a2631dda6e84b3f8d60cf0.js:20:100949

**Comment by hugoabernier** [comment]
Closing this issue as incomplete.

If you're still experiencing this issue, feel free to open a new issue. When you do, I encourage you to take the time to fill the issue template provided so we can get you the help you deserve.

Please note that authors do not get automatically notified unless you fill the issue template.
