### ISSUE TITLE
First day of week for the React calendar sample

### ISSUE THREAD

**Issue by hristochr** [pnp/sp-dev-fx-webparts#1262]
Hi, I am using the react calendar sample and it works nicely. The webpart is one site, while the calendar is on another one. The regional settings on both sites are Dutch (Belgium) and first day of week Monday. However, the webpart still displays Sunday as the first day of the week.

How can I set the first day of the week to be Monday in the webpart?

**Comment by nanddeepn** [comment]
Hi,
In the file: https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-calendar/src/webparts/calendar/components/Calendar.tsx

Just before line 56
`const localizer = BigCalendar.momentLocalizer(moment);`

Add below code:
`
moment.locale('nl', {
    week: {
        dow: 1,
        doy: 1,
    },
});
`

In this context: 
- 'nl' represents the required locale name (Dutch in this case, hope I am correct here)
- 'dow' represents, that the week will start with Monday. 
- 'doy' works together with 'dow' to determine first week of the year. 

Hope this helps!

**Comment by hristochr** [comment]
Thank you @nanddeepn but trying to bundle --ship returns multiple errors:

`
src/webparts/_themes.scss
 51:71  ×  Unexpected missing end-of-source newline   no-missing-end-of-source-newline

src/webparts/calendar/components/Calendar.module.scss
  5:1   ×  Unexpected unknown pseudo-class selector ":export"               selector-pseudo-class-no-unknown
  6:3   ×  Expected "themeDark" to be "themedark"                           property-case
  6:3   ×  Unexpected unknown property "themeDark"                          property-no-unknown
 21:55  ×  Unexpected whitespace at end of line                             no-eol-whitespace
 22:14  ×  Expected single space before "{"                                 block-opening-brace-space-before
 26:9   ×  Expected single space after ":" with a single-line declaration   declaration-colon-space-after



[11:44:05] Finished subtask 'stylelint' after 1.42 s
[11:44:05] Starting subtask 'copy-static-assets'...
[11:44:05] Starting subtask 'sass'...
[11:44:05] Warning - [sass] src\webparts\calendar\components\calendar.scss: filename should end with module.sass or module.scss
[11:44:05] Finished subtask 'copy-static-assets' after 196 ms
[11:44:06] Finished subtask 'sass' after 371 ms
[11:44:06] Starting subtask 'tslint'...
[11:44:07] [tslint] tslint version: 5.12.1
[11:44:08] Starting subtask 'tsc'...
[11:44:08] [tsc] typescript version: 3.2.4
[11:44:25] Finished subtask 'tsc' after 17 s
[11:44:26] Finished subtask 'tslint' after 21 s
[11:44:26] Starting subtask 'post-copy'...
[11:44:26] Finished subtask 'post-copy' after 597 μs
[11:44:26] Starting subtask 'collectLocalizedResources'...
[11:44:26] Finished subtask 'collectLocalizedResources' after 5.62 ms
[11:44:26] Starting subtask 'configure-webpack'...
[11:44:27] Finished subtask 'configure-webpack' after 826 ms
[11:44:27] Starting subtask 'webpack'...
[11:45:34] Warning - [webpack] 'dist':
./lib/webparts/calendar/components/Calendar.js 76:0-13
"export 'locale' (imported as 'moment') was not found in 'moment'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:60:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compilation.js:1356:24)
    at hooks.finishModules.callAsync.err (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compilation.js:1164:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compilation.js:1159:28)
    at hooks.make.callAsync.err (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compiler.js:622:17)
    at _err0 (eval at create (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compilation.js:1091:12)
    at processModuleDependencies.err (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compilation.js:1003:9)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./lib/webparts/calendar/CalendarWebPart.js
./lib/webparts/calendar/components/Calendar.js 101:8-21
"export 'locale' (imported as 'moment') was not found in 'moment'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:60:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compilation.js:1356:24)
    at hooks.finishModules.callAsync.err (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compilation.js:1164:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compilation.js:1159:28)
    at hooks.make.callAsync.err (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compiler.js:622:17)
    at _err0 (eval at create (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compilation.js:1091:12)
    at processModuleDependencies.err (C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\webpack\lib\Compilation.js:1003:9)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./lib/webparts/calendar/CalendarWebPart.js
./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\moment\src\lib\locale'
resolve './locale' in 'C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\moment\src\lib\locale'
  using description file: C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\moment\package.json (relative path: ./src/lib/locale)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\moment\package.json (relative path: ./src/lib/locale/locale)
      as directory
        C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\moment\src\lib\locale\locale doesn't exist
[C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar\node_modules\moment\src\lib\locale\locale]
 @ ./node_modules/moment/src/lib/locale/locales.js
 @ ./node_modules/moment/src/lib/locale/locale.js
 @ ./node_modules/moment/src/moment.js
 @ ./lib/webparts/calendar/CalendarWebPart.js

[11:45:34] Finished subtask 'webpack' after 1.1 min
[11:45:34] Starting subtask 'configure-webpack-external-bundling'...
[11:45:34] Finished subtask 'configure-webpack-external-bundling' after 1.3 ms
[11:45:34] Starting subtask 'copy-assets'...
[11:46:11] Finished subtask 'copy-assets' after 37 s
[11:46:11] Starting subtask 'write-manifests'...
[11:46:12] Finished subtask 'write-manifests' after 1.2 s
[11:46:12] Finished 'bundle' after 2.13 min
[11:46:13] ==================[ Finished ]==================
Warning - [sass] src/webparts/calendar/components/calendar.scss: filename should end with module.sass or module.scss
Warning - [webpack] 'dist':
./lib/webparts/calendar/components/Calendar.js 76:0-13
"export 'locale' (imported as 'moment') was not found in 'moment'
    at HarmonyImportSpecifierDependency._getErrors (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getWarnings (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:60:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compilation.js:1356:24)
    at hooks.finishModules.callAsync.err (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compilation.js:1164:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compilation.js:1159:28)
    at hooks.make.callAsync.err (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compilation.js:1091:12)
    at processModuleDependencies.err (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compilation.js:1003:9)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./lib/webparts/calendar/CalendarWebPart.js
./lib/webparts/calendar/components/Calendar.js 101:8-21
"export 'locale' (imported as 'moment') was not found in 'moment'
    at HarmonyImportSpecifierDependency._getErrors (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getWarnings (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:60:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compilation.js:1356:24)
    at hooks.finishModules.callAsync.err (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compilation.js:1164:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compilation.js:1159:28)
    at hooks.make.callAsync.err (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compilation.js:1091:12)
    at processModuleDependencies.err (C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/webpack/lib/Compilation.js:1003:9)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
 @ ./lib/webparts/calendar/CalendarWebPart.js
./node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in 'C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/moment/src/lib/locale'
resolve './locale' in 'C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/moment/src/lib/locale'
  using description file: C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/moment/package.json (relative path: ./src/lib/locale)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/moment/package.json (relative path: ./src/lib/locale/locale)
      as directory
        C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/moment/src/lib/locale/locale doesn't exist
[C:/Users/AIR28546/OneDrive - OneVirtualOffice/Repos/Spfx-Web-Parts-Clone/react-calendar/node_modules/moment/src/lib/locale/locale]
 @ ./node_modules/moment/src/lib/locale/locales.js
 @ ./node_modules/moment/src/lib/locale/locale.js
 @ ./node_modules/moment/src/moment.js
 @ ./lib/webparts/calendar/CalendarWebPart.js

[11:46:13] Project react-calendar version:1.0.2
[11:46:13] Build tools version:3.12.1
[11:46:13] Node version:v8.17.0
[11:46:13] Total duration:2.25 min
[11:46:13] Task warnings:2
The build failed because a task wrote output to stderr.
Exiting with exit code: 1
PS C:\Users\AIR28546\OneDrive - OneVirtualOffice\Repos\Spfx-Web-Parts-Clone\react-calendar>`

**Comment by hugoabernier** [comment]
Closing this issue as invalid.

If you're still experiencing this issue, feel free to open a new issue and take the time to fill the issue template provided so that we can help you better. Information such as author and environment go a long way to help route the issue to the right people and get your issue resolved. Incomplete issues are automatically closed.

Thanks for your understanding.

**Comment by Wizz4rrd** [comment]
> Hi, In the file: https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-calendar/src/webparts/calendar/components/Calendar.tsx
> 
> Just before line 56 `const localizer = BigCalendar.momentLocalizer(moment);`
> 
> Add below code: `moment.locale('nl', { week: { dow: 1, doy: 1, }, });`
> 
> In this context:
> 
> * 'nl' represents the required locale name (Dutch in this case, hope I am correct here)
> * 'dow' represents, that the week will start with Monday.
> * 'doy' works together with 'dow' to determine first week of the year.
> 
> Hope this helps!

Hi @nanddeepn 
Tried what you mentionned here above, build and shipped a new package, yet this didn't change the first day of the week. Site settings and profile wise everything is set to first day of the week = monday. 

Do you have any other suggestions?
