### ISSUE TITLE
Please update node-sass to the latest version

### ISSUE THREAD

**Issue by Zireael** [pnp/sp-dev-fx-webparts#1454]
Hi,
Can you update node-sass in your deep dependencies to the latest version?
Old version uses old node-gyp that uses Python 2 (Python 2 has been killed off in Dec 2019).
Alternatively, can you switch to dart-sass and get rid of node-gyp dependency entirely? That would save people lots of problems with node-gyp.
I'm only after a working example of how to pack a webpart to import it into Sharepoint (365).

## Sample (which sample are you having trouble with)
All, for example helloworld-webpart

## Expected or Desired Behavior
`yarn install `works

## Observed Behavior

```
C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'V:\\Programming\\JavaScript\\Programming\\Projects\\Sharepoint\\sp-dev-fx-webparts\\tutorials\\tutorial-getting-started\\helloworld-webpart\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.7.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python38\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];     
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "V:\\Programming\\JavaScript\\Programming\\Projects\\Sharepoint\\sp-dev-fx-webparts\\tutorials\\tutorial-getting-started\\helloworld-webpart\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\sp-dev-fx-webparts\tutorials\tutorial-getting-started\helloworld-webpart\node_modules\node-sass
gyp ERR! node -v v14.7.0
```

## Steps to Reproduce

Have up to date Node (v12 or 14) and Python (v3) installed

1. Clone repository
2. `yarn install`

# Environment Details (*Development & Target environment*)

- **OS**: [e.g. Windows 10
- **Tooling**:  Node v14, Python 3

**Comment by PathToSharePoint** [comment]
The samples are built on the SharePoint Framework, a tool provided by Microsoft.

The current version (SPFx 1.11) only supports Node.js LTS 10.x, not v12 and even less v14.

You can read more about the SPFx development environment here:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment
