### ISSUE TITLE
react-my-sites - Old version of Node.js

### ISSUE THREAD

**Issue by ekstam** [pnp/sp-dev-fx-webparts#1457]
## Sample (which sample are you talking about)
react-my-sites

## Authors
@joaojmendes 

## Suggestion (the more details, the better)
Hi! I would love to try out your web part but I'm having some issues with deployment (I'll probably create another issue regarding that).

While building I had to downgrade Node.js to 8.17.0 in order to create a successfull build. 8.17.0 is end of life as I understand it (https://nodejs.org/en/download/releases/ // https://nodejs.org/en/about/releases/)?
After downgrade, the build finished successfully.

```
\sp-dev-fx-webparts\samples\react-my-teams>gulp build
Error: Your dev environment is running NodeJS version v10.20.1 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=8.9.4 <9.0.0

at SPWebBuildRig.initialize (c:\svn\GitHub\sp-dev-fx-webparts\samples\react-my-teams\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:25:19)
at SPWebBuildRig.initialize (c:\svn\GitHub\sp-dev-fx-webparts\samples\react-my-teams\node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js:15:15)
at Object.exports.initialize (c:\svn\GitHub\sp-dev-fx-webparts\samples\react-my-teams\node_modules\@microsoft\sp-build-web\lib\index.js:23:17)
at Object.<anonymous> (c:\svn\GitHub\sp-dev-fx-webparts\samples\react-my-teams\gulpfile.js:29:7)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
```

```
c:\GitHub\sp-dev-fx-webparts\samples\react-my-teams>gulp build
Build target: DEBUG
[23:57:33] Using gulpfile c:\GitHub\sp-dev-fx-webparts\samples\react-my-teams\gulpfile.js
[23:57:33] Starting gulp
[23:57:33] Starting 'build'...
[23:57:33] Starting subtask 'configure-sp-build-rig'...
[23:57:33] Finished subtask 'configure-sp-build-rig' after 4.28 ms
[23:57:33] Starting subtask 'pre-copy'...
[23:57:33] Finished subtask 'pre-copy' after 30 ms
[23:57:33] Starting subtask 'copy-static-assets'...
[23:57:33] Starting subtask 'sass'...
[23:57:33] Finished subtask 'copy-static-assets' after 34 ms
[23:57:33] Finished subtask 'sass' after 135 ms
[23:57:33] Starting subtask 'tslint'...
[23:57:33] [tslint] tslint version: 5.9.1
[23:57:33] Starting subtask 'tsc'...
[23:57:33] [tsc] typescript version: 2.4.2
[23:57:35] Finished subtask 'tsc' after 1.84 s
[23:57:35] Starting subtask 'api-extractor'...
[23:57:35] Finished subtask 'api-extractor' after 1.03 ms
[23:57:35] Finished subtask 'tslint' after 2.46 s
[23:57:35] Starting subtask 'post-copy'...
[23:57:35] Finished subtask 'post-copy' after 507 μs
[23:57:35] Finished 'build' after 2.64 s
[23:57:36] ==================[ Finished ]==================
[23:57:36] Project my-teams version:0.0.1
[23:57:36] Build tools version:3.8.33
[23:57:36] Node version:v8.17.0
[23:57:36] Total duration:6.17 s

c:\GitHub\sp-dev-fx-webparts\samples\react-my-teams>gulp bundle --ship
Build target: SHIP
[23:57:50] Using gulpfile c:\GitHub\sp-dev-fx-webparts\samples\react-my-teams\gulpfile.js
[23:57:50] Starting gulp
[23:57:50] Starting 'bundle'...
[23:57:50] Starting subtask 'configure-sp-build-rig'...
[23:57:50] Finished subtask 'configure-sp-build-rig' after 4.06 ms
[23:57:50] Starting subtask 'pre-copy'...
[23:57:50] Finished subtask 'pre-copy' after 27 ms
[23:57:50] Starting subtask 'copy-static-assets'...
[23:57:50] Starting subtask 'sass'...
[23:57:50] Finished subtask 'copy-static-assets' after 30 ms
[23:57:50] Finished subtask 'sass' after 111 ms
[23:57:50] Starting subtask 'tslint'...
[23:57:50] [tslint] tslint version: 5.9.1
[23:57:51] Starting subtask 'tsc'...
[23:57:51] [tsc] typescript version: 2.4.2
[23:57:53] Finished subtask 'tsc' after 1.9 s
[23:57:53] Starting subtask 'api-extractor'...
[23:57:53] Finished subtask 'api-extractor' after 522 μs
[23:57:53] Finished subtask 'tslint' after 2.42 s
[23:57:53] Starting subtask 'post-copy'...
[23:57:53] Finished subtask 'post-copy' after 558 μs
[23:57:53] Starting subtask 'collectLocalizedResources'...
[23:57:53] Finished subtask 'collectLocalizedResources' after 3.17 ms
[23:57:53] Starting subtask 'configure-webpack'...
[23:57:53] Finished subtask 'configure-webpack' after 730 ms
[23:57:53] Starting subtask 'webpack'...
[23:57:56] Finished subtask 'webpack' after 2.83 s
[23:57:56] Starting subtask 'configure-webpack-external-bundling'...
[23:57:56] Finished subtask 'configure-webpack-external-bundling' after 1.05 ms
[23:57:56] Starting subtask 'copy-assets'...
[23:57:56] Finished subtask 'copy-assets' after 39 ms
[23:57:56] Starting subtask 'write-manifests'...
[23:57:57] Finished subtask 'write-manifests' after 901 ms
[23:57:57] Finished 'bundle' after 7.09 s
[23:57:58] ==================[ Finished ]==================
[23:57:58] Project my-teams version:0.0.1
[23:57:58] Build tools version:3.8.33
[23:57:58] Node version:v8.17.0
[23:57:58] Total duration:11 s

c:\GitHub\sp-dev-fx-webparts\samples\react-my-teams>gulp package-solution --ship
Build target: SHIP
[23:58:13] Using gulpfile c:\GitHub\sp-dev-fx-webparts\samples\react-my-teams\gulpfile.js
[23:58:13] Starting gulp
[23:58:13] Starting 'package-solution'...
[23:58:13] Starting subtask 'configure-sp-build-rig'...
[23:58:13] Finished subtask 'configure-sp-build-rig' after 3.98 ms
[23:58:13] Starting subtask 'package-solution'...
[23:58:13] [package-solution] Found manifest: c:\GitHub\sp-dev-fx-webparts\samples\react-my-teams\temp\deploy\58468a8f-40f4-4759-a6f8-493a56bdaaf7.json
[23:58:13] [package-solution] Found client-side build resource: my-teams-web-part_8984531d74a6226873e4aea9598c20ea.js
[23:58:13] [package-solution] Found client-side build resource: react-my-teams-myteamswebpartstrings_en-us_5d42e9c8771a59cd1f90f73940e04699.js
[23:58:13] Verifying configuration...
[23:58:13] Done!
[23:58:13]
[23:58:13] Normalizing solution information...
[23:58:13] Attempting creating component definitions for {1} manifests
[23:58:13] Created component definitions for {1} manifests
[23:58:13] config.solution.features not set! Instead generating a feature for each component.
[23:58:13] Creating feature for My Teams...
[23:58:13] Done!
[23:58:13]
[23:58:13] Reading custom Feature XML...
[23:58:13] Done!
[23:58:13]
[23:58:13] Validating App Package...
[23:58:13] Done!
[23:58:13]
[23:58:13] Reading resources...
[23:58:13] Done!
[23:58:13]
[23:58:13] Reading Sharepoint Assets & Creating XML...
[23:58:13] Done!
[23:58:13]
[23:58:13] Writing solution XML to sharepoint\solution\debug...
[23:58:13] Cleaned sharepoint\solution\debug
[23:58:13] Created file: sharepoint\solution\debug\AppManifest.xml
[23:58:13] Created file: sharepoint\solution\debug\_rels\.rels
[23:58:13] Created file: sharepoint\solution\debug\58468a8f-40f4-4759-a6f8-493a56bdaaf7\WebPart_58468a8f-40f4-4759-a6f8-493a56bdaaf7.xml
[23:58:13] Created file: sharepoint\solution\debug\ClientSideAssets\my-teams-web-part_8984531d74a6226873e4aea9598c20ea.js
[23:58:13] Created file: sharepoint\solution\debug\feature_58468a8f-40f4-4759-a6f8-493a56bdaaf7.xml
[23:58:13] Created file: sharepoint\solution\debug\[Content_Types].xml
[23:58:13] Created file: sharepoint\solution\debug\_rels\feature_58468a8f-40f4-4759-a6f8-493a56bdaaf7.xml.rels
[23:58:13] Created file: sharepoint\solution\debug\feature_58468a8f-40f4-4759-a6f8-493a56bdaaf7.xml.config.xml
[23:58:13] Created file: sharepoint\solution\debug\ClientSideAssets.xml.config.xml
[23:58:13] Created file: sharepoint\solution\debug\ClientSideAssets.xml
[23:58:13] Created file: sharepoint\solution\debug\_rels\ClientSideAssets.xml.rels
[23:58:13] Created file: sharepoint\solution\debug\ClientSideAssets\react-my-teams-myteamswebpartstrings_en-us_5d42e9c8771a59cd1f90f73940e04699.js
[23:58:13] Created file: sharepoint\solution\debug\_rels\AppManifest.xml.rels
[23:58:13] Created file: sharepoint\solution\my-teams.sppkg
[23:58:13] Done!
[23:58:13]
[23:58:13] ALL DONE!
[23:58:13]
[23:58:13] Finished subtask 'package-solution' after 166 ms
[23:58:13] Finished 'package-solution' after 172 ms
[23:58:13] ==================[ Finished ]==================
[23:58:14] Project my-teams version:0.0.1
[23:58:14] Build tools version:3.8.33
[23:58:14] Node version:v8.17.0
[23:58:14] Total duration:3.71
```

**Comment by hugoabernier** [comment]
@ekstam thanks for your suggestion. You can use the Office 365 CLI `spfx project upgrade` command to upgrade the project to a newer version of SPFx which supports a later a version of NodeJs.

Please note that we also welcome contributions in this repository. If you upgrade the solution, feel free to submit a PR for your newer version.

**Comment by PathToSharePoint** [comment]
I just did a test and everything looks fine on my end. I first tested Node.js v10.18.0 installed on my computer, then upgraded to v10.22.0 and again it worked fine.
