### ISSUE TITLE
Error in react provision assets

### ISSUE THREAD

**Issue by Rrodferi** [pnp/sp-dev-fx-webparts#1510]
## Expected or Desired Behavior

Generate sppkg when i execute command "gulp package-solution" for web part "react-provision-assets"

## Observed Behavior

When I execute "gulp package-solution", I get the following error:

**Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.**
    at Object.createPackage [as default] (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/packageSolution/createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/PackageSolutionTask.js:135:36)
    at DestroyableTransform.prefinish (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:198:13)
    at prefinish (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:286:20)
    at DestroyableTransform.emit (events.js:203:15)
    at /home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
[15:17:56] Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/packageSolution/createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/PackageSolutionTask.js:135:36)
    at DestroyableTransform.prefinish (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:198:13)
    at prefinish (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:286:20)
    at DestroyableTransform.emit (events.js:203:15)
    at /home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
[15:17:56] Error - 'package-solution' sub task errored after 10 ms 
 No manifests were found in '*.json'. Ensure a build has completed successfully and that paths.manifestsMatch is correct
[15:17:56] 'package-solution' errored after 14 ms
[15:17:56] 
[15:17:56] ==================[ Finished ]==================
Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/packageSolution/createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/PackageSolutionTask.js:135:36)
    at DestroyableTransform.prefinish (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:198:13)
    at prefinish (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:286:20)
    at DestroyableTransform.emit (events.js:203:15)
    at /home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/packageSolution/createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/@microsoft/sp-build-core-tasks/lib/packageSolution/PackageSolutionTask.js:135:36)
    at DestroyableTransform.prefinish (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:198:13)
    at prefinish (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (/home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:286:20)
    at DestroyableTransform.emit (events.js:203:15)
    at /home/vsonline/workspace/sp-dev-fx-webparts/samples/react-provision-assets/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error - 'package-solution' sub task errored after 10 ms 
 No manifests were found in '*.json'. Ensure a build has completed successfully and that paths.manifestsMatch is correct

## Steps to Reproduce

Follow the readme steps to compile and generate the package solution:
- npm i
- gulp build --ship
- gulp prepare-solution This custom gulp task copies the file e89b5ad5-9ab5-4730-a66b-e1f68994598c.json from the folder sharepoint\temp\ to temp\deploy in order to prepare the package.
- gulp package-solution

**Comment by Rrodferi** [comment]
Hi,
I found the error. The problem is that the file "e89b5ad5-9ab5-4730-a66b-e1f68994598c.json" isnt exists in path "sharepoint/temp".   Could you upload it?
Regards!

**Comment by hugoabernier** [comment]
Hi @Rrodferi , thanks for investigating the issue.  The authors of the sample don't get automatically notified unless you mention them in the issue (hence the authors section in the issue template).

I hope that the authors can help here?

**Comment by Rrodferi** [comment]
Thanks @hugoabernier ! Hi @nanddeepn , could you review this? Thank you very much :)

**Comment by nanddeepn** [comment]
Hi @Rrodferi 
Thanks for reporting. I will look in to this.

**Comment by nanddeepn** [comment]
Hi @hugoabernier 
Please review the PR. 
Previously the location of json was referring to path `sharepoint\temp\e89b5ad5-9ab5-4730-a66b-e1f68994598c.json` and it was being ignored from `.gitignore`
