### ISSUE TITLE
gulp serve error " ReferenceError: internalBinding is not defined " 

### ISSUE THREAD

**Issue by tyh77** [pnp/sp-dev-fx-webparts#1613]
## Sample (which sample are you having trouble with)
**angularelements-helloworld**

## Authors

@VesaJuvonen 

## Expected or Desired Behavior
Just wanted to see how the sample Angular Elements app runs

## Observed Behavior
```
PS C:\source\repos\sp-dev-fx-webparts\samples\angularelements-helloworld> gulp serve
ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (C:\source\repos\sp-dev-fx-webparts\samples\angularelements-helloworld\node_modules\natives\index.js:137:5)
    at require (C:\source\repos\sp-dev-fx-webparts\samples\angularelements-helloworld\node_modules\natives\index.js:110:12)
    at util.js:25:21
    at req_ (C:\source\repos\sp-dev-fx-webparts\samples\angularelements-helloworld\node_modules\natives\index.js:137:5)
    at require (C:\source\repos\sp-dev-fx-webparts\samples\angularelements-helloworld\node_modules\natives\index.js:110:12)
    at fs.js:42:21
    at req_ (C:\source\repos\sp-dev-fx-webparts\samples\angularelements-helloworld\node_modules\natives\index.js:137:5)
    at Object.req [as require] (C:\source\repos\sp-dev-fx-webparts\samples\angularelements-helloworld\node_modules\natives\index.js:54:10)
    at Object.<anonymous> (C:\source\repos\sp-dev-fx-webparts\samples\angularelements-helloworld\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
```

I wonder if it's related to these issues:
- https://github.com/pnp/sp-dev-fx-webparts/issues/1163
- https://github.com/pnp/sp-dev-fx-webparts/issues/967

I made sure to install Node v10 because v9, 11, and 12 and explicitly stated as incompatible.

## Steps to Reproduce
1. Cloned the repo
2. Already had npm, gulp, and yo installed
3. At git repo, ran command: `npm i`
4. Then ran `gulp serve`

## Environment Details (*Development & Target environment*)
- npm -v: 10.22.1
- gulp -v:3.9.1 (CLI is v2.3.0)
- SP generator -v: 1.11.0

**Comment by tyh77** [comment]
After re-reading the other issue: https://github.com/pnp/sp-dev-fx-webparts/issues/1163, I can confirm that installing `natives@1.1.6` does the trick:
`npm i natives@1.1.6`

But this is still a workaround
