### ISSUE TITLE
react-birthdays webpart gives the following error [SPLoaderError.loadComponentError]

### ISSUE THREAD

**Issue by sudeshkumara** [pnp/sp-dev-fx-webparts#1618]
Could you please anyone can help me with this issue? I've no idea where the local host is coming from. I manually checked the configuration files as well. But nothing was found that related to that url.  (Node version:v10.19.0)

These are the steps I've followed.

npm install
gulp build
gulp bundle --ship
gulp package-solution --ship
Add and Deploy Package to AppCatalog
and allows Graph API SCOPES

```
Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "e629ef30-a9ec-4713-b39a-2cfa8b323902" (BirthdaysWebPart). Original error: Failed to load URL 'https://localhost:4321/lib/controls/HappyBirthdayCard/loc/en-us.js' for resource 'ControlStrings' in component 'e629ef30-a9ec-4713-b39a-2cfa8b323902' (BirthdaysWebPart). There was a network problem. Make sure that you are running 'gulp serve' and you have run 'gulp trust-dev-cert'.

INNERERROR:
Failed to load URL 'https://localhost:4321/lib/controls/HappyBirthdayCard/loc/en-us.js' for resource 'ControlStrings' in component 'e629ef30-a9ec-4713-b39a-2cfa8b323902' (BirthdaysWebPart). There was a network problem. Make sure that you are running 'gulp serve' and you have run 'gulp trust-dev-cert'.
CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:849606)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:994861)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1035757)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1031802)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1024069
```

**Comment by hugoabernier** [comment]
@sudeshkumara we need you to open a new issue using the issue template that we provided in order for us to help you.

I'm going to close this issue as incomplete. Feel free to open a new issue. And, when you do, make sure to provide all the information we ask in the [new bug template](https://github.com/pnp/sp-dev-fx-webparts/issues/new?assignees=&labels=type%3Abug&template=bug.md&title=)
