### ISSUE TITLE
react-accordion: Cannot Find Module 'is-obj'

### ISSUE THREAD

**Issue by edmundo-martinez** [pnp/sp-dev-fx-webparts#1703]
## Sample
Accordion Web Part (react-accordion)

## Authors
@hugoabernier 

## Expected or Desired Behavior

Adding web part to new page and configure it to reference specific custom list

## Observed Behavior

Latest version (2.2.0.0) based on commit e6cd0b17 from Feb 8, 2021 produces an "Error: Cannot Find Module 'is-obj'".
Technical Details copied and pasted below:
[SPLoaderError.loadComponentError]:
Failed to load component "97a28c00-64ee-4ec7-b373-723e39069a96" (ReactAccordionWebPart). Original error: Failed to load entry point from component "97a28c00-64ee-4ec7-b373-723e39069a96" (ReactAccordionWebPart). Original error: Error loading https://component-id.invalid/97a28c00-64ee-4ec7-b373-723e39069a96_2.2.0
	Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Cannot find module 'is-obj'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Work\GitHub\sp-dev-fx-webparts\samples\react-accordion\node_modules\dot-prop\index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Work\GitHub\sp-dev-fx-webparts\samples\react-accordion\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\parser.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

INNERERROR:
Failed to load entry point from component "97a28c00-64ee-4ec7-b373-723e39069a96" (ReactAccordionWebPart). Original error: Error loading https://component-id.invalid/97a28c00-64ee-4ec7-b373-723e39069a96_2.2.0
	Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Cannot find module 'is-obj'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Work\GitHub\sp-dev-fx-webparts\samples\react-accordion\node_modules\dot-prop\index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Work\GitHub\sp-dev-fx-webparts\samples\react-accordion\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\parser.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:19896)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:164857)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:202176)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_f2a6d5a2ddacad6fe99f72579e74f146.js:65:198221)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_01c8e48deab9f3a3784f.js:1:66061  

## Steps to Reproduce

1. Add an app
2. Click on ''react-accordion-client-side-solution"
3. Add a page
4. Add web part titled "React Accordion App'
5. See error, as listed above

# Environment Details (*Development & Target environment*)

- **OS**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.20.1
- **Browser(s)**: Chromium Edge v88
- **Tooling**: VS Code

## Additional context
None

**Comment by hugoabernier** [comment]
Thanks for providing your environment details. I can confirm that you're running in the right environment to use the web part, and I've tested the web part using the same environment settings.

The only thing I can think of is that the web part requires a list with the appropriate columns to be configured in order to use the web part. It does not handle errors well, which would explain the behavior you may experience.

I'm not the author of the sample (I just process the pull requests), but I would suggest that you look at the deployment instructions to make sure you have the required list. You may also want to upgrade the issue description to include the actual authors of the sample so they can get notified and -- hopefully -- help you further.

Let us know how it works out?

**Comment by hugoabernier** [comment]
I'll assume that the issue is resolved due to no response. If you're still experiencing the issue, please do not hesitate to create a new issue with more information so we can get you the help you deserve.
