### ISSUE TITLE
React-Script-Editor

### ISSUE THREAD

**Issue by voltar** [pnp/sp-dev-fx-webparts#1734]
Hi, I did the npm install and then tried to run gulp serve, but I get a ReferenceError:primordials is not defined at fs.js:52:5

fs.js:52
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:52:5
    at req_ (C:\development\sharepoint\sp-dev-fx-webparts\samples\react-script-editor\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\development\sharepoint\sp-dev-fx-webparts\samples\react-script-editor\node_modules\natives
\index.js:55:10)
    at Object.<anonymous> (C:\development\sharepoint\sp-dev-fx-webparts\samples\react-script-editor\node_modules\gulp\node_mo
dules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)

zanet@GRZ_LENOVO1 MINGW64 /c/development/sharepoint/sp-dev-fx-webparts/samples/react-script-editor (master)

what should I do?

**Comment by hugoabernier** [comment]
We'd love to help you with this, but you'll need to provide us with all the information we requested in the issue template.

I'll close this issue as incomplete. Please feel free to open a new issue (type: Bug) and provide all the information requested.

Please note that incomplete issues will be automatically closed.

Thank you for your understanding,
