### ISSUE TITLE
sp-dev-fx-webparts/samples/react-list-form/ Manifest not found for component id "f9e737b7-f0df-4597-ba8c-3060f82380db" and version "1.10.0".

### ISSUE THREAD

**Issue by n1k17a** [pnp/sp-dev-fx-webparts#1780]
Hello. I try to deploy and test react-list-form
I did next steps
npm install
gulp build
![image](https://user-images.githubusercontent.com/78145746/112042942-c42f2280-8b50-11eb-8142-ad846ed17978.png)

gulp bundle --ship
![image](https://user-images.githubusercontent.com/78145746/112043232-1ec87e80-8b51-11eb-92bb-a1b3f4780eeb.png)

gulp package-solution --ship
![image](https://user-images.githubusercontent.com/78145746/112043357-3ef83d80-8b51-11eb-89f3-a2b86c45779d.png)
 
Solution is deployed to Sharepoint successfully 
![image](https://user-images.githubusercontent.com/78145746/112045180-386ac580-8b53-11eb-99e0-daa1364403db.png)

But when i have tryed add web part to my page, next error is showed on webpage

Something went wrong

If the problem persists, contact the site administrator and give them the information in Technical Details.

Technical Details

[SPLoaderError.loadComponentError]:
***Failed to load component "48e2d130-7eb7-4ee9-aa23-5ddbdfd175b1" (ListFormWebPart).
Original error: ***Manifest not found for component id "f9e737b7-f0df-4597-ba8c-3060f82380db" and version "1.10.0".

***INNERERROR:
***Manifest not found for component id "f9e737b7-f0df-4597-ba8c-3060f82380db" and version "1.10.0".
***CALLSTACK:
Error
   at t._generateErrorStackForIE (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:356:16078)
   at t (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:356:15614)
   at t (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:807:22166)
   at e.buildErrorWithVerboseLog (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:807:14402)
   at e.buildLoadComponentError (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:807:10817)
   at Anonymous function (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:807:62074)
   at A (http://server-sp.dc1.local/_layouts/15/next/spclient/10.sp-pages-search.js:8:1743)
   at k (http://server-sp.dc1.local/_layouts/15/next/spclient/10.sp-pages-search.js:8:1831)
   at Anonymous function (http://server-sp.dc1.local/_layouts/15/next/spclient/10.sp-pages-search.js:8:5649)
   at h (http://server-sp.dc1.local/_layouts/15/next/spclient/10.sp-pages-search.js:8:344)

![image](https://user-images.githubusercontent.com/78145746/112046154-58e74f80-8b54-11eb-8167-71d5c1bf6096.png)

**Comment by hugoabernier** [comment]
We cannot accept incomplete submissions. Please feel free to open a new issue and submit all the required information as per the issue template that is provided when you create a new issue. 

Thanks for your understanding.
