### ISSUE TITLE
react-list-form: Manifest not found for component id "f9e737b7-f0df-4597-ba8c-3060f82380db" and version "1.10.0"

### ISSUE THREAD

**Issue by n1k17a** [pnp/sp-dev-fx-webparts#1781]
## Sample
react-list-form

## Authors

react-list-form | Dany Wyss
react-list-form | Harsha Vardhini (@harshagracy)
react-list-form | Ryan Schouten (@shrpntknight)
react-list-form | Abderahman Moujahid
react-list-form | Kman1131
react-list-form | Fredrik Thorild @fthorild

## Expected or Desired Behavior

Successful add web part and connect to list

## Observed Behavior
Get error when try add webpart to web page

## Steps to Reproduce

1. Build Solution
2. Add it to sharepoint 2019 on premises
3. Create new page
4. Add webpart

Hello. I try to deploy and test react-list-form
I did next steps
npm install
gulp build

![image](https://user-images.githubusercontent.com/78145746/112120540-05621980-8bc7-11eb-8551-7b5b34a4069e.png)

gulp bundle --ship
![image](https://user-images.githubusercontent.com/78145746/112120594-1448cc00-8bc7-11eb-94b4-a1e2bb68abfb.png)

gulp package-solution --ship
![image](https://user-images.githubusercontent.com/78145746/112120619-1e6aca80-8bc7-11eb-9d4f-82876a289e0d.png)

Solution is deployed to Sharepoint successfully
![image](https://user-images.githubusercontent.com/78145746/112120648-262a6f00-8bc7-11eb-9035-d60a99e704bc.png)

But when i have tryed add web part to my page, next error is showed on webpage

Something went wrong

If the problem persists, contact the site administrator and give them the information in Technical Details.

Technical Details

[SPLoaderError.loadComponentError]:
***Failed to load component "48e2d130-7eb7-4ee9-aa23-5ddbdfd175b1" (ListFormWebPart).
Original error: ***Manifest not found for component id "f9e737b7-f0df-4597-ba8c-3060f82380db" and version "1.10.0".

***INNERERROR:
***Manifest not found for component id "f9e737b7-f0df-4597-ba8c-3060f82380db" and version "1.10.0".
***CALLSTACK:
Error
at t._generateErrorStackForIE (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:356:16078)
at t (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:356:15614)
at t (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:807:22166)
at e.buildErrorWithVerboseLog (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:807:14402)
at e.buildLoadComponentError (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:807:10817)
at Anonymous function (http://server-sp.dc1.local/_layouts/15/next/spclient/en-us/sp-pages-assembly.js?uniqueId=EtjOS:807:62074)
at A (http://server-sp.dc1.local/_layouts/15/next/spclient/10.sp-pages-search.js:8:1743)
at k (http://server-sp.dc1.local/_layouts/15/next/spclient/10.sp-pages-search.js:8:1831)
at Anonymous function (http://server-sp.dc1.local/_layouts/15/next/spclient/10.sp-pages-search.js:8:5649)
at h (http://server-sp.dc1.local/_layouts/15/next/spclient/10.sp-pages-search.js:8:344)

# Environment Details (*Development & Target environment*)

- **OS**: [Windows Server 2019]
- **Target Environment**: [ SharePoint Server 2019]
- **Framework**: [Node.js 10.24.0]
- **Browser(s)**: [Version 89.0.4389.90 (Official Build) (64-bit)]
- **Tooling**: [VS Code]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

**Comment by hugoabernier** [comment]
Thanks for your issue @n1k17a , but the web part you are referring to only works with SharePoint online, as is indicated in the **compatibility** section of the `README.md`.

This web part was built using SPFx 1.10; SharePoint 2019 only supports up to SPFx 1.4.1.

**Comment by n1k17a** [comment]
Thank. Was inattentive. It is very sad that the offline version is no longer supported
