### ISSUE TITLE
React-Script-Editor : UnhandledPromiseRejectionWarning error

### ISSUE THREAD

**Issue by saurabhcmathur** [pnp/sp-dev-fx-webparts#1829]
Hi,

i am trying to use the react-script-editor for SharePoint online. It works fine in my local environment but when i run gulp bundle -- ship I get an error.

(node:12668) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'toJson' of undefined
[18:20:01] Starting subtask 'webpack'...

(node:35956) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toJson' of undefined
    at webpack (C:\SPFX\New folder\react-script-editor\node_modules\@microsoft\gulp-core-build-webpack\lib\WebpackTask.js:73:47)
    at finalCallback (C:\SPFX\New folder\react-script-editor\node_modules\webpack\lib\Compiler.js:220:39)
    at hooks.done.callAsync.err (C:\SPFX\New folder\react-script-editor\node_modules\webpack\lib\Compiler.js:268:23)
    at _err0 (eval at create (C:\SPFX\New folder\react-script-editor\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Immediate.setImmediate [as _onImmediate] (C:\SPFX\New folder\react-script-editor\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:76:13)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:35956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function 
without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:35956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
About to exit with code: 0
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1

------x---------- tsconfig.json

{
    "extends": "./node_modules/@microsoft/rush-stack-compiler-3.3/includes/tsconfig-web.json",
    "compilerOptions": {
      "target": "es5",
      "forceConsistentCasingInFileNames": true,
      "module": "esnext",
      "moduleResolution": "node",
      "jsx": "react",
      "declaration": true,
      "emitDecoratorMetadata": true,
      "sourceMap": true,
      "skipLibCheck": true,
      "outDir": "lib",
      "inlineSources": false,
      "strictNullChecks": false,
      "noUnusedLocals": false,
      "typeRoots": [
        "./node_modules/@types",
        "./node_modules/@microsoft"
      ],
      "types": [
        "es6-promise",
        "webpack-env"
      ],
      "lib": [
        "es5",
        "dom",
        "es2015.collection"
      ]
    },
    "include": [
      "src/**/*.ts"
    ],
    "exclude": [
      "node_modules",

      "lib"
    ]
  }

**Comment by saurabhcmathur** [comment]
Node Version v8.17.0
