### ISSUE TITLE
React-Script-Editor : Unhandled Promise Rejection Warning error

### ISSUE THREAD

**Issue by saurabhcmathur** [pnp/sp-dev-fx-webparts#1830]
## Sample
react-script-editor

## Authors
Mikael Svenson ([@mikaelsvenson](http://www.twitter.com/mikaelsvenson), [techmikael.com](techmikael.com))

## Expected or Desired Behavior
No error should be displayed and it should build the project successfully.

## Observed Behavior
Getting error while running  gulp bundle -- ship

(node:35956) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toJson' of undefined
at webpack (C:\SPFX\New folder\react-script-editor\node_modules@microsoft\gulp-core-build-webpack\lib\WebpackTask.js:73:47)
at finalCallback (C:\SPFX\New folder\react-script-editor\node_modules\webpack\lib\Compiler.js:220:39)
at hooks.done.callAsync.err (C:\SPFX\New folder\react-script-editor\node_modules\webpack\lib\Compiler.js:268:23)
at _err0 (eval at create (C:\SPFX\New folder\react-script-editor\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), :9:1)
at Immediate.setImmediate [as _onImmediate] (C:\SPFX\New folder\react-script-editor\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:76:13)
at
at runMicrotasksCallback (internal/process/next_tick.js:122:5)
at _combinedTickCallback (internal/process/next_tick.js:132:7)
at process._tickCallback (internal/process/next_tick.js:181:9)
(node:35956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function
without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:35956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
About to exit with code: 0
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1

## Steps to Reproduce

1.  Download the project react-script-editor
2.  Run npm install 
3.  Run gulp build
4.  Run gulp bundle -- ship
4. See an error

# Environment Details (*Development & Target environment*)

- **OS**:  Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v8.17.0
- **Browser(s)**: Chrome v88.0.4324.150
- **Tooling**: VS Code

## Additional context
I am trying to use the react-script editor for SharePoint online. It works fine in my local environment but when I run gulp bundle -- ship I get the error.

**Comment by Abderahman88** [comment]
Do you have the same errors when you do `gulp serve` ?

**Comment by saurabhcmathur** [comment]
No I go not get error while doing gulp serve or gulp build . Only when I do
gulp bundle -- ship I get the error and as of the it's not getting packaged
for production.

**Comment by Abderahman88** [comment]
I have no issues with `gulp bundle --ship`

Maybe you could try upgrading node to v10 and try again.

**Comment by saurabhcmathur** [comment]
Ok upgrading the node to v10.24.1 fixed the issue. 
Thanks!!
