### ISSUE TITLE
react-organisation-chart - Unexpected token error during eslint

### ISSUE THREAD

**Issue by cpoiris** [pnp/sp-dev-fx-webparts#1947]
### Sample

react-organisation-chart

### Author(s)

@joaojmendes

### What happened?

I would like to test the "Organization Chart" web part on SharePoint Server 2019 to see if it meets our needs. Therefore, I'm trying to package it in order to install it in the App Catalog but I'm getting an error when bundling it with `gulp bundle --ship`.

I have to say I'm quite new in Node.js and its ecosystem and I didn't make any changes in the sample code.

```
C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart>gulp bundle --ship
Build target: SHIP
[10:22:18] Using gulpfile C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\gulpfile.js
[10:22:18] Starting gulp
[10:22:18] Starting 'bundle'...
[10:22:18] Starting subtask 'configure-sp-build-rig'...
[10:22:18] Finished subtask 'configure-sp-build-rig' after 6.83 ms
[10:22:18] Starting subtask 'pre-copy'...
[10:22:18] Finished subtask 'pre-copy' after 8.74 ms
[10:22:18] Starting subtask 'eslint'...
C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\node_modules\eslint\lib\cli-engine\cli-engine.js:421
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\node_modules\eslint\lib\cli-engine\index.js:3:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\node_modules\eslint\lib\api.js:8:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\CLIEngine.js:5:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
[10:22:18] Error - Unknown
 Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Unexpected token {
Referenced from: C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\.eslintrc.json
[10:22:19] ==================[ Finished ]==================
Error - Unknown
 Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Unexpected token {
Referenced from: C:/dev_cp/Github/sp-dev-fx-webparts/samples/react-organization-chart/.eslintrc.json
[10:22:19] Project react-organization-chart version: 0.0.1
[10:22:19] Build tools version: 3.2.7
[10:22:19] Node version: v8.17.0
[10:22:19] Total duration: 4.23 s
[10:22:19] Task errors: 2
[10:22:19] Error - 'undefined' errored after
 "orchestration aborted"
```

### Steps to reproduce

1. `cd pathToSampleFolder`
2. `npm install`
3. `gulp bundle --ship`

### Expected behavior

I would like to get a `.sppkg` file in order to install it in the App Catalog.

### Target SharePoint environment

SharePoint Server 2019 (on-premise)

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v8.17.0

**Comment by joaojmendes** [comment]
Hi,

Try using node version 10.

Thanks.


From: Cédric P. ***@***.***>
Date: Friday, 25 June 2021 at 09:38
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: [pnp/sp-dev-fx-webparts] react-organisation-chart - Unexpected token error during eslint (#1947)
Sample

react-organisation-chart

Author(s)

@joaojmendes<https://github.com/joaojmendes>

What happened?

I would like to test the "Organization Chart" web part on SharePoint Server 2019 to see if it meets our needs. Therefore, I'm trying to package it in order to install it in the App Catalog but I'm getting an error when bundling it with gulp bundle --ship.

I have to say I'm quite new in Node.js and its ecosystem and I didn't make any changes in the sample code.

Build target: SHIP

[10:22:18] Using gulpfile C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\gulpfile.js

[10:22:18] Starting gulp

[10:22:18] Starting 'bundle'...

[10:22:18] Starting subtask 'configure-sp-build-rig'...

[10:22:18] Finished subtask 'configure-sp-build-rig' after 6.83 ms

[10:22:18] Starting subtask 'pre-copy'...

[10:22:18] Finished subtask 'pre-copy' after 8.74 ms

[10:22:18] Starting subtask 'eslint'...

C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\node_modules\eslint\lib\cli-engine\cli-engine.js:421

    } catch {

            ^



SyntaxError: Unexpected token {

    at createScript (vm.js:80:10)

    at Object.runInThisContext (vm.js:139:10)

    at Module._compile (module.js:617:28)

    at Object.Module._extensions..js (module.js:664:10)

    at Module.load (module.js:566:32)

    at tryModuleLoad (module.js:506:12)

    at Function.Module._load (module.js:498:3)

    at Module.require (module.js:597:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\node_modules\eslint\lib\cli-engine\index.js:3:23)

    at Module._compile (module.js:653:30)

    at Object.Module._extensions..js (module.js:664:10)

    at Module.load (module.js:566:32)

    at tryModuleLoad (module.js:506:12)

    at Function.Module._load (module.js:498:3)

    at Module.require (module.js:597:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\node_modules\eslint\lib\api.js:8:23)

    at Module._compile (module.js:653:30)

    at Object.Module._extensions..js (module.js:664:10)

    at Module.load (module.js:566:32)

    at tryModuleLoad (module.js:506:12)

    at Function.Module._load (module.js:498:3)

    at Module.require (module.js:597:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> ***@***.***\experimental-utils\dist\ts-eslint\CLIEngine.js:5:18)

    at Module._compile (module.js:653:30)

    at Object.Module._extensions..js (module.js:664:10)

[10:22:18] Error - Unknown

 Failed to load plugin ***@***.***' declared in '.eslintrc.json': Unexpected token {

Referenced from: C:\dev_cp\Github\sp-dev-fx-webparts\samples\react-organization-chart\.eslintrc.json

[10:22:19] ==================[ Finished ]==================

Error - Unknown

 Failed to load plugin ***@***.***' declared in '.eslintrc.json': Unexpected token {

Referenced from: C:/dev_cp/Github/sp-dev-fx-webparts/samples/react-organization-chart/.eslintrc.json

[10:22:19] Project react-organization-chart version: 0.0.1

[10:22:19] Build tools version: 3.2.7

[10:22:19] Node version: v8.17.0

[10:22:19] Total duration: 4.23 s

[10:22:19] Task errors: 2

[10:22:19] Error - 'undefined' errored after

 "orchestration aborted"```



### Steps to reproduce



1. `cd pathToSampleFolder`

2. `npm install`

3. `gulp bundle --ship`



### Expected behavior



I would like to get a `.sppkg` file in order to install it in the App Catalog.



### Target SharePoint environment



SharePoint Server 2019 (on-premise)



### Developer environment



Windows



### Browsers



- [ ] Internet Explorer

- [ ] Microsoft Edge

- [ ] Google Chrome

- [ ] FireFox

- [ ] Safari

- [ ] mobile (iOS/iPadOS)

- [ ] mobile (Android)

- [X] not applicable

- [ ] other (enter in the "Additional environment details" area below)



### Node.js version



v8.17.0



### Additional environment details



_No response_

**Comment by cpoiris** [comment]
Hello João,

Switching to Node.js 10 did the trick. I was able to create a `.sppkg` file.

Thank you very much for your quick reply and for your help!

**Comment by itrazar** [comment]
Hello,

I have the same problem and run this sample using dev container. I just cannot seem to upgrade to node 10 due to nvm missing in the container. Any idea's i can try?

Thanks
