### ISSUE TITLE
react-calendar - Error: Cannot find module '@microsoft/sp-build-web'

### ISSUE THREAD

**Issue by eawong-coca-cola** [pnp/sp-dev-fx-webparts#2171]
### Sample

react-calendar

### Author(s)

@Abderahman88, @Eli-Schei, @mohammadamer, @joaojmendes, @derhallim, @nanddeepn, @mohammadamer

### What happened?

After running npm install then gulp build, I get hit with this error consistently. I'm unsure what to do to solve for this.

I believe I have all the right versions as well for gulp , yo, npm & spfx Node js matches (1.10 - 10.16)

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\O41159\sp-dev-fx-webparts\samples\react-calendar\gulpfile.js:11:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

### Steps to reproduce

1.clone samples repo
2. npm install
3. gulp build

### Expected behavior

to progress and build the sample

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v10.16.3

**Comment by eawong-coca-cola** [comment]
and maybe for more helpful context, I try and install it manually and I get this

npm i @microsoft/sp-build-web
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @microsoft/sp-build-web@1.10.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:

**Comment by eawong-coca-cola** [comment]
and running npm i gives me this
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @microsoft/sp-core-library@1.10.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'react-calendar'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:

**Comment by eawong-coca-cola** [comment]
i got around this in the first by running the suggested npm higher up in the root so not in the samples

npm {install something} within the Users\(user)\sp-dev-fx-webparts 

now I face a new issue per usual 
[13:44:22] Using gulpfile ~\sp-dev-fx-webparts\samples\react-calendar\gulpfile.js
[13:44:22] Starting 'build'...
[13:44:22] Starting gulp
[13:44:22] Starting subtask 'pre-copy'...
[13:44:22] Finished subtask 'pre-copy' after 74 ms
[13:44:22] Starting subtask 'stylelint'...
[13:44:23] Finished subtask 'stylelint' after 850 ms
[13:44:23] Starting subtask 'copy-static-assets'...
[13:44:23] Starting subtask 'sass'...
[13:44:23] Error - sass - src\controls\Event\Event.module.scss(1,9): error Error: Can't find stylesheet to import.
  ╷
1 │ @import "~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\controls\Event\Event.module.scss 1:9  root stylesheet
[13:44:23] Error - sass - src\webparts\calendar\components\Calendar.module.scss(1,9): error Error: Can't find stylesheet to import.
  ╷
1 │ @import "~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\webparts\calendar\components\Calendar.module.scss 1:9  root stylesheet
[13:44:23] Error - sass - src\webparts\calendar\components\calendar.scss(1,9): error Error: Can't find stylesheet to import.
  ╷
1 │ @import "~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\webparts\calendar\components\calendar.scss 1:9  root stylesheet
[13:44:23] Error - sass - src\webparts\calendar\components\Year.module.scss(1,9): error Error: Can't find stylesheet to import.
  ╷
1 │ @import "~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\webparts\calendar\components\Year.module.scss 1:9  root stylesheet
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
[13:44:23] Error - 'sass' sub task errored after 269 ms 
 Can't find stylesheet to import.
  ╷
1 │ @import "~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\controls\Event\Event.module.scss 1:9  root stylesheet
[13:44:23] 'build' error

**Comment by Abderahman88** [comment]
Hi @eawong-coca-cola,

You need to take following steps (Node v10):

1) Clone `sp-dev-fx-webparts` repo
2) Open the folder `react-calendar` in Visual Studio Code
![image](https://user-images.githubusercontent.com/36161889/146690330-b6df8035-2efe-4b3c-a4b7-9c7008312572.png)
3) Run `npm install`
![image](https://user-images.githubusercontent.com/36161889/146690417-274575ef-4d1b-402a-8169-e9d49453ab15.png)
4) If everything is installed, run `gulp serve`
![image](https://user-images.githubusercontent.com/36161889/146690456-35a5a1d5-8565-4791-9725-0960cdcb952b.png)
