### ISSUE TITLE
Gulp Serve is throwing ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by whinney17** [pnp/sp-dev-fx-webparts#2233]
### Sample

react-script-editor

### Author(s)

@wobba

### What happened?

After running npm install successfully, I'm getting an error when running gulp serve:
PS C:\Users\morga\sp-dev-fx-webparts\samples\react-script-editor> gulp serve
ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (C:\Users\morga\sp-dev-fx-webparts\samples\react-script-editor\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\morga\sp-dev-fx-webparts\samples\react-script-editor\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\morga\sp-dev-fx-webparts\samples\react-script-editor\node_modules\gulp\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)

### Steps to reproduce

1. npm install
2. gulp serve

### Expected behavior

Test web part in local browser

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.19.0

### Additional environment details

Gulp v: 
CLI version: 2.3.0
Local version: 3.9.1

**Comment by ColonelSand3rs** [comment]
I also get the same issue. 
I have tried multiple versions of Node and Gulp but cant seem to get the right combination that this needs

**Comment by adreno-abhi** [comment]
I am facing the same issue with node 14.18.3. 
All toolchains as per new sharepoint environment setup guidelines.

**Comment by whinney17** [comment]
I was able to install version 10.18 of Node and that worked. Now facing a new issue but finally was able to test on localhost.

**Comment by wobba** [comment]
I use node v14.17.5 and have no issues building it. And It's using SPFx v1.13.1. 

gulp reports
```
CLI version: 2.3.0
Local version: 4.0.2
```

**Comment by Rajesh-Pradhan** [comment]
I'm using  node v14.17.5 and It's using SPFx v1.14.0. I'm getting "primordials is not defined"

gulp reports

CLI version: 2.3.0
Local version: 4.0.2
