### ISSUE TITLE
react-organization-chart sample - gulp serve throws "ReferenceError: primordials is not defined"

### ISSUE THREAD

**Issue by adreno-abhi** [pnp/sp-dev-fx-webparts#2235]
### Sample

react-organization-chart

### Author(s)

@joaojmendes

### What happened?

after npm install, on running gulp serve following error message is displayed:

C:\Users\HP\source\repos\SPFXOrgChart>gulp serve
ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (C:\Users\HP\source\repos\SPFXOrgChart\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\HP\source\repos\SPFXOrgChart\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\HP\source\repos\SPFXOrgChart\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)

### Steps to reproduce

1. npm install
2. gulp serve
3.

### Expected behavior

gulp serve serves the webpart and is accessible

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.18.3

### Additional environment details

Gulp version : 
CLI version: 2.3.0
Local version: 3.9.1

Sharepoint generator:
@microsoft/generator-sharepoint@1.13.1

**Comment by joaojmendes** [comment]
Hello,

This sp-dev-fx-webparts/samples/react-organization-chart at main · pnp/sp-dev-fx-webparts (github.com)<https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-organization-chart> is compatible with SP2019 and the SPFx version supported is 1.4.1

Please, install Node Version 10 and run npm install again.

Thank you!
João

From: Abhijeet ***@***.***>
Date: Thursday, 3 February 2022 at 09:33
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: [pnp/sp-dev-fx-webparts] react-organization-chart sample - gulp serve throws "ReferenceError: primordials is not defined" (Issue #2235)
Sample

react-organization-chart

Author(s)

@joaojmendes<https://github.com/joaojmendes>

What happened?

after npm install, on running gulp serve following error message is displayed:

C:\Users\HP\source\repos\SPFXOrgChart>gulp serve
ReferenceError: primordials is not defined
at fs.js:40:5
at req_ (C:\Users\HP\source\repos\SPFXOrgChart\node_modules\natives\index.js:143:24)
at Object.req [as require] (C:\Users\HP\source\repos\SPFXOrgChart\node_modules\natives\index.js:55:10)
at Object. (C:\Users\HP\source\repos\SPFXOrgChart\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:93:18)

Steps to reproduce

  1.  npm install
  2.  gulp serve
  3.

Expected behavior

gulp serve serves the webpart and is accessible

Target SharePoint environment

SharePoint Online

Developer environment

Windows

Browsers

  *   Internet Explorer
  *   Microsoft Edge
  *   Google Chrome
  *   FireFox
  *   Safari
  *   mobile (iOS/iPadOS)
  *   mobile (Android)
  *   not applicable
  *   other (enter in the "Additional environment details" area below)

Node.js version

v14.18.3

Additional environment details

Gulp version :
CLI version: 2.3.0
Local version: 3.9.1

Sharepoint generator:
@***@***.***

**Comment by adreno-abhi** [comment]
Thanks for the quick response. is there an updated repository for the latest toolchains supported by SPFx.

**Comment by adreno-abhi** [comment]
Thanks @joaojmendes for the quick reply.
Is there an updated repository for the latest toolchain for SPFx

**Comment by joaojmendes** [comment]
You can start to view here Overview of the SharePoint Framework (SPFx) | Microsoft Docs<https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview>, Supported extensibility platforms - overview | Microsoft Docs<https://docs.microsoft.com/en-us/sharepoint/dev/spfx/supported-extensibility-platforms-overview>


From: Abhijeet ***@***.***>
Date: Thursday, 3 February 2022 at 09:44
To: pnp/sp-dev-fx-webparts ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: Re: [pnp/sp-dev-fx-webparts] react-organization-chart sample - gulp serve throws "ReferenceError: primordials is not defined" (Issue #2235)

Thanks for the quick response. is there an updated repository for the latest toolchains supported by SPFx.

**Comment by adreno-abhi** [comment]
Thanks
