### ISSUE TITLE
React-Company-Stories Bug

### ISSUE THREAD

**Issue by mihaihera** [pnp/sp-dev-fx-webparts#2432]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-company-stories

### Author(s)

@hugoabernier

### What happened?

Hello,

After creating the stories list and implementing the solution (stories), when I add it as a web part to my sharepoint page I get the following error.

### Steps to reproduce

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to load entry point from component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry

INNERERROR:
Failed to load entry point from component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:70:214295)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:8874)
    at Function.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:45955)
    at Function.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:42072)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_c13a3fd9296251f1459f.js:1:60147

### Expected behavior

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to load entry point from component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry

INNERERROR:
Failed to load entry point from component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:70:214295)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:8874)
    at Function.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:45955)
    at Function.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:42072)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_c13a3fd9296251f1459f.js:1:60147

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to load entry point from component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry

INNERERROR:
Failed to load entry point from component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:70:214295)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:8874)
    at Function.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:45955)
    at Function.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:42072)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_c13a3fd9296251f1459f.js:1:60147

### Additional environment details

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to load entry point from component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry

INNERERROR:
Failed to load entry point from component "076de2d7-509f-469c-ab79-42f88611ae13" (SharePointStoriesWebPart). Original error: Failed to execute 'define' on 'CustomElementRegistry': the name "mgt-flyout" has already been used with this registry
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:70:214295)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:8874)
    at Function.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:45955)
    at Function.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_6c97ae89d85f664614b24d840404a1b0.js:71:42072)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_c13a3fd9296251f1459f.js:1:60147

**Comment by mihaihera** [comment]
The author: Luis Mañez (MVP, [ClearPeople](http://www.clearpeople.com/), @luismanez)
