### ISSUE TITLE
react-staff-directory SPFx gulp serve webpack issue

### ISSUE THREAD

**Issue by mhijazi** [pnp/sp-dev-fx-webparts#2780]
### Disclaimer

Yes

### Sample

react-staff-directory

### Author(s)

@hugoabernier

### Question

Hello,
I'm having issue running gulp serve and bundle on react-staff-directory SPFx project, I have upgraded the project to the latest SPFx as per cli-microsoft365, but with no luck keeps getting the error below.

I tried to use the latest webpack 5, also tried webpack 4.

Not sure if it's related to webpack or something else.

I'm able to gulp serve a hello-world project normally

My environment specs
-------------------------------
Windows 11

node -v
v14.15.5

npm -v
6.14.11

+-- @microsoft/generator-sharepoint@1.14.0
+-- @pnp/cli-microsoft365@5.3.0
+-- gulp-cli@2.3.0
`-- yo@4.3.0
-------------------------------

`
```
[13:55:30] Error: Cannot find module 'webpack/lib/ParserHelpers'
Require stack:
- D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\hashed-folder-copy-plugin\lib\HashedFolderCopyPlugin.js
- D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\hashed-folder-copy-plugin\lib\index.js
- D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\webpackConfigurationPlugin\WebpackConfigurationGenerator.js
- D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\webpackConfigurationPlugin\WebpackConfigurationPlugin.js
- D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\spfx-heft-plugins\lib\spfxHeftPlugin.js
- D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\spfx-heft-plugins\lib\index.js
- D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\sp-build-core-tasks\lib\webpack\ConfigureWebpackTask.js
- D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\sp-build-web\node_modules\@microsoft\sp-build-core-tasks\lib\index.js
- D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\sp-build-web\lib\index.js
- D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\gulpfile.js
- C:\Users\502852\AppData\Roaming\npm\node_modules\gulp-cli\lib\shared\require-or-import.js
- C:\Users\502852\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- C:\Users\502852\AppData\Roaming\npm\node_modules\gulp-cli\index.js
- C:\Users\502852\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at lazy (D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\import-lazy\index.js:3:33)
    at Object.get (D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\import-lazy\index.js:11:22)
    at handler (D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\hashed-folder-copy-plugin\lib\HashedFolderCopyPlugin.js:104:53)
    at SyncHook.eval [as call] (eval at create (D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\sp-build-web\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\sp-build-web\node_modules\tapable\lib\Hook.js:154:20)
    at NormalModuleFactory.createParser (D:\code\pnp sp-dev-fx-webparts main samples-react-staffdirectory\node_modules\@microsoft\sp-build-web\node_modules\webpack\lib\NormalModuleFactory.js:487:31)
About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code ` 
```
@hugoabernier

**Comment by milanholemans** [comment]
Hi @mhijazi 

Seems like I was able to successfully upgrade the project. Ran it locally and seems to work.
If you want I can create a PR for this so you can try my version (I'm using Node v14).

**Comment by mhijazi** [comment]
@milanholemans Thank you buddy, I think we have done the same steps for upgrade haven't seen major differences.

You aren't using webpack which is required when running gulp serve, when I remove it from devDepedencies I'm getting below error.

I think the problem is with my development environment or build tools; which windows are you using (mine is 11) and which vsbuilldtools version 2015, 2017, or 2019?

when running gulp serve
```
Error: Cannot find module 'webpack'
Require stack:
- D:\code\react-staffdirectory\node_modules\@rushstack\module-minifier-plugin\lib\ModuleMinifierPlugin.js
- D:\code\react-staffdirectory\node_modules\@rushstack\module-minifier-plugin\lib\index.js
- D:\code\react-staffdirectory\node_modules\@microsoft\spfx-heft-plugins\lib\spfxManifests\manifestFileBuilder\ManifestsFileBuilder.js
- D:\code\react-staffdirectory\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\devDeployPlugin\SpDevDeploy.js
- D:\code\react-staffdirectory\node_modules\@microsoft\spfx-heft-plugins\lib\plugins\devDeployPlugin\DevDeployPlugin.js
- D:\code\react-staffdirectory\node_modules\@microsoft\spfx-heft-plugins\lib\spfxHeftPlugin.js
- D:\code\react-staffdirectory\node_modules\@microsoft\spfx-heft-plugins\lib\index.js
- D:\code\react-staffdirectory\node_modules\@microsoft\sp-build-core-tasks\lib\webpack\ConfigureWebpackTask.js
- D:\code\react-staffdirectory\node_modules\@microsoft\sp-build-core-tasks\lib\index.js
- D:\code\react-staffdirectory\node_modules\@microsoft\sp-build-web\lib\index.js
- D:\code\react-staffdirectory\gulpfile.js
- C:\Users\MHijazi\AppData\Roaming\npm\node_modules\gulp-cli\lib\shared\require-or-import.js
- C:\Users\MHijazi\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- C:\Users\MHijazi\AppData\Roaming\npm\node_modules\gulp-cli\index.js
- C:\Users\MHijazi\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (D:\code\react-staffdirectory\node_modules\@rushstack\module-minifier-plugin\lib\ModuleMinifierPlugin.js:26:30)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\code\\react-staffdirectory\\node_modules\\@rushstack\\module-minifier-plugin\\lib\\ModuleMinifierPlugin.js',
    'D:\\code\\react-staffdirectory\\node_modules\\@rushstack\\module-minifier-plugin\\lib\\index.js',
    'D:\\code\\react-staffdirectory\\node_modules\\@microsoft\\spfx-heft-plugins\\lib\\spfxManifests\\manifestFileBuilder\\ManifestsFileBuilder.js',
    'D:\\code\\react-staffdirectory\\node_modules\\@microsoft\\spfx-heft-plugins\\lib\\plugins\\devDeployPlugin\\SpDevDeploy.js',
    'D:\\code\\react-staffdirectory\\node_modules\\@microsoft\\spfx-heft-plugins\\lib\\plugins\\devDeployPlugin\\DevDeployPlugin.js',
    'D:\\code\\react-staffdirectory\\node_modules\\@microsoft\\spfx-heft-plugins\\lib\\spfxHeftPlugin.js',
    'D:\\code\\react-staffdirectory\\node_modules\\@microsoft\\spfx-heft-plugins\\lib\\index.js',
    'D:\\code\\react-staffdirectory\\node_modules\\@microsoft\\sp-build-core-tasks\\lib\\webpack\\ConfigureWebpackTask.js',
    'D:\\code\\react-staffdirectory\\node_modules\\@microsoft\\sp-build-core-tasks\\lib\\index.js',
    'D:\\code\\react-staffdirectory\\node_modules\\@microsoft\\sp-build-web\\lib\\index.js',
    'D:\\code\\react-staffdirectory\\gulpfile.js',
    'C:\\Users\\MHijazi\\AppData\\Roaming\\npm\\node_modules\\gulp-cli\\lib\\shared\\require-or-import.js',
    'C:\\Users\\MHijazi\\AppData\\Roaming\\npm\\node_modules\\gulp-cli\\lib\\versioned\\^4.0.0\\index.js',
    'C:\\Users\\MHijazi\\AppData\\Roaming\\npm\\node_modules\\gulp-cli\\index.js',
    'C:\\Users\\MHijazi\\AppData\\Roaming\\npm\\node_modules\\gulp-cli\\bin\\gulp.js'
  ]
}
```

**Comment by mhijazi** [comment]
@milanholemans Do I need to install webpack or not? and if yes which version?

**Comment by milanholemans** [comment]
@mhijazi did it work?
