### ISSUE TITLE
REACT-ACCORDION - 

### ISSUE THREAD

**Issue by martini0463** [pnp/sp-dev-fx-webparts#3077]
### Disclaimer

Yes

### Sample

REACT-ACCORDION

### Author(s)

@AbhishekGarg @gautamdsheth

### What happened?

[19:46:04] Node flags detected: --experimental-worker
[19:46:04] Respawned to PID: 2404
Error: Your dev environment is running NodeJS version v10.24.1 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=12.13.0 <13.0.0 || >=14.15.0 <15.0.0 || >=16.13.0 <17.0.0
    at SPWebBuildRig.initialize (C:\Users\martini\Documents\SPWebParts\accordion_samples\react-accordion\node_modules\@microsoft\sp-build-web\lib\SPBuildRig.js:27:19)
    at Object.initialize (C:\Users\martini\Documents\SPWebParts\accordion_samples\react-accordion\node_modules\@microsoft\sp-build-web\lib\index.js:36:17)
    at Object.<anonymous> (C:\Users\martini\Documents\SPWebParts\accordion_samples\react-accordion\gulpfile.js:7:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

### Steps to reproduce

1. download the code
2. nvm use  10.24.1 (Currently using 64-bit executable)
But I've tried with all of these with the same "luck" 
_16.18.0, 14.20.1, 13.14.0 and 11.15.0 (not acceptable by the solution), 12.22.9_
3. npm i
4. npm install gulp-cli yo@3 @microsoft/generator-sharepoint --global _as the gulp was not available_
5.  Now I'm able to run gulp build, gulp test or gulp serve **but** there is an error that I'm not able to handle.

IF I TRY WITH A NEWEST VERION OF NODE I GET ANOTHER ISSUE:
Starting subtask 'lint'...
[18:33:56] Error - [lint] TypeError: rushStackCompiler.LintRunner is not a constructor
[18:33:56] Error - 'lint' sub task errored after 68

(PS C:\Users\martini\Documents\SPWebParts\accordion_samples\react-accordion> gulp build
Build target: DEBUG
[18:33:55] Using gulpfile ~\Documents\SPWebParts\accordion_samples\react-accordion\gulpfile.js
[18:33:55] Starting 'build'...
[18:33:55] Starting gulp
[18:33:55] Starting subtask 'pre-copy'...
[18:33:55] Finished subtask 'pre-copy' after 95 ms
[18:33:55] Starting subtask 'copy-static-assets'...
[18:33:55] Starting subtask 'sass'...
[18:33:56] Finished subtask 'sass' after 557 ms
[18:33:56] Starting subtask 'lint'...
[18:33:56] Error - [lint] TypeError: rushStackCompiler.LintRunner is not a constructor
[18:33:56] Error - 'lint' sub task errored after 687 ms
 rushStackCompiler.LintRunner is not a constructor
[18:33:56] Starting subtask 'tsc'...
[18:33:56] [tsc] typescript version: 3.3.4000
[18:33:56] 'build' errored after 1.38 s
[18:33:56]
About to exit with code: 1
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1)

### Expected behavior

I'm expecting to build and run the project (gulp test/gulp serve)

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Paste the results of SPFx doctor

m365 spfx doctor -o text

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.10.0
√ Node v10.24.1
√ yo v3.1.1
√ gulp-cli v2.3.0
√ bundled typescript used

### Additional environment details

node -v
v10.24.1

npm list -g --dept=0
C:\Program Files\nodejs
+-- @microsoft/generator-sharepoint@1.15.2
+-- @pnp/cli-microsoft365@5.8.0
+-- gulp-cli@2.3.0
+-- npm@6.14.12
`-- yo@3.1.1

**Comment by petkir** [comment]
@martini0463 this issue is related to #3073 

![image](https://user-images.githubusercontent.com/13123689/197358535-6f8f2b7d-634e-4542-bed5-f04ebfae73b1.png)

for a quick fix please change the following lines in ```package.json```
from:
```
"@microsoft/sp-build-web": "1.15.2",
"@microsoft/sp-webpart-workbench": "1.12.1",
```
to:
```
"@microsoft/sp-build-web": "1.10.0",
"@microsoft/sp-webpart-workbench": "1.10.0",
```

Please delete ```package-lock.json``` and ```node_modules``` folder 
and start with a new installation ```npm i```, I think this would work

**Comment by martini0463** [comment]
@petkir THANK YOU VERY MUCH Peter.
The suggested solution fixes the issue
