### ISSUE TITLE
Debugging with VS Code Chrome extension in hosted workbench

### ISSUE THREAD

**Issue by ypcode** [pnp/sp-dev-fx-webparts#359]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
No exception expected

#### Observed Behavior
An uncaught exception is raised when debugging using the Chrome debugger extension for SPFx in hosted workbench

```
sp-webpart-workbench-assembly_en-us_3d3f03aaa2acf2b6ab6e4204e7f30bd0.js:167
Error: Sys.InvalidOperationException: Operation is not valid due to the current state of the object.
shellcoreming2am_95e32178.js:65
    at Function.Error.create (https://r1.res.office365.com/o365/versionless/shellcoreming2am_95e32178.js:65:13)
    at Function.Error.invalidOperation (https://r1.res.office365.com/o365/versionless/shellcoreming2am_95e32178.js:137:19)
    at Function._o365cl.a.b (https://r1.res.office365.com/o365/versionless/shellcoreming2am_95e32178.js:2479:13695)
    at _o365sg2c.s.b.f (https://r1.res.office365.com/o365/versionless/shellcoreprimeg2m_791c159d.js:20:1728)
    at _o365sg2c.s.a (https://r1.res.office365.com/o365/versionless/shellcoreprimeg2m_791c159d.js:20:877)
    at Function.O365Shell.InvokeSuiteAPILoaded (https://r1.res.office365.com/o365/versionless/shellcoreprimeg2m_791c159d.js:22:15326)
    at _o365sg2p.Loader.h (https://r1.res.office365.com/o365/versionless/shellplusg2m_5b8477a.js:36:10503)
```

#### Steps to Reproduce
Use the documented method to debug SPFx webparts in the workbench using VS Code and Google Chrome debugger extension

**Comment by bcameron1231** [comment]
Hi @ypcode , we are going through cleaning up some of these issues here. Noticed this is an extremely old ticket. Is this still relevant, or can this be closed?

**Comment by ypcode** [comment]
Hi guys, indeed it’s extremely old I did not even remember anything about it ☺️. I never seen it again recently so I think that can be closed 👍

**Comment by PopWarner** [comment]
Thanks @ypcode! :)
