### ISSUE TITLE
react-content-query-online - Dependency issues due to dependency updates.

### ISSUE THREAD

**Issue by ChrisLizon** [pnp/sp-dev-fx-webparts#3678]
### Disclaimer

Yes

### Sample

react-content-query-online

### Contributor(s)

@spplante @hugoabernier

### What happened?

Can't compile for various issues. 

So as far as I can tell the cosmiconfig package is using the nullishing coalescing assignment operator, which isn't supported until NodeJS 15.

https://node.green/#ES2021-features-Logical-Assignment-----basic-support

It looks like somewhere the stylelint package is using Cosmiconfig version 8.1.3, and cosmicconfig dropped nodejs 10 support in version 8. The last version of Stylelint to use a 7.x branch of cosmiconfig was version 14.16.1

Going through the build process there's a few Microsoft packages that are too new to be used with node 10 as well. I

### Steps to reproduce

1. Clone a fresh copy of repo
2. Follow build instructions. 

- npm install --global gulp
- npm install
- gulp build
```
PS C:\Code\ReactContentQuery\sp-dev-fx-webparts\samples\react-content-query-online> gulp build
{ Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Code\ReactContentQuery\sp-dev-fx-webparts\samples\react-content-query-online\node_modules\@rushstack\worker-pool\lib\WorkerPool.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
```
- set environment variable..
`   $env:NODE_OPTIONS="--experimental-worker"`
    
    
 - gulp build
    
```    
    C:\Code\ReactContentQuery\sp-dev-fx-webparts\samples\react-content-query-online\node_modules\stylelint\node_modules\cosmiconfig\dist\index.js:69
  const overrideOptions = metaConfig.config ?? {};
                                             ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Code\ReactContentQuery\sp-dev-fx-webparts\samples\react-content-query-online\node_modules\stylelint\lib\createStylelint.js:3:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

### Expected behavior

Package should be produced. 

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v10.24.1

### What version of Node.js is required by the sample?

v10

### Paste the results of SPFx doctor

```
PS C:\Code\ReactContentQuery\sp-dev-fx-webparts\samples\react-content-query-online> m365 spfx doctor -o text

CLI for Microsoft 365 SharePoint Framework doctor
Verifying configuration of your system for working with the SharePoint Framework

√ SharePoint Framework v1.11.0
√ Node v10.24.1
√ yo v3.1.1
× gulp should be removed
× gulp-cli not found
√ bundled typescript used
 
Recommended fixes:

- npm un -g gulp
- npm i -g gulp-cli@2
```

### Additional environment details

gulp vs gulp-cli makes no difference from what I've seen.

**Comment by ChrisLizon** [comment]
Submitted PR #3679 which has fixed the issues for me.
