### ISSUE TITLE
react-graph-telephonedirectory - 

### ISSUE THREAD

**Issue by phezo** [pnp/sp-dev-fx-webparts#3711]
### Disclaimer

Yes

### Sample

react-graph-telephonedirectory

### Contributor(s)

@Dips365 @a1mery @mrkhandev

### Question

I am new to spfx development, many thanks for the samples and advice, it is very much appreciated :)

In your expert opinion, what would the best approach be to deploying this solution in terms of the best practice for hosting the gulp server, Also I see a certificate error in my tenant when the server is running, also I reported an issue 
and cleared it by resetting the  gulp server, however I am now seeing that edge is working and chrome is not, I will investigate further :)

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Script error for: 586d82f7-79c3-4fc6-be7b-290fa1e4f1f6_1.3.0/ControlStrings
http://requirejs.org/docs/errors.html#scripterror

CALL STACK:
Error: Script error for: 586d82f7-79c3-4fc6-be7b-290fa1e4f1f6_1.3.0/ControlStrings
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/isolated-web-part-application-assembly_en-us_dbb152f8e2f90ae9a9cbdbe9b4e0836f.js:68:345758), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/isolated-web-part-application-assembly_en-us_dbb152f8e2f90ae9a9cbdbe9b4e0836f.js:68:345758), <anonymous>:30:244)

**Comment by phezo** [comment]
Issue resolved with 
gulp clean
gulp bundle --ship
gulp package-solution --ship
Works as expected now with no certificate issues and no need to run local server :)
