### ISSUE TITLE
 "Error: Cannot find module 'worker_threads'"

### ISSUE THREAD

**Issue by dearcaroline** [pnp/sp-dev-fx-webparts#3782]
### Disclaimer

Yes

### Sample

react-tiles-v2

### Contributor(s)

@omarelanis

### Question

When trying to run any gulp commands, I'm getting the following error:

`{ Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\REDACTED\sp-dev-fx-webparts\samples\react-tiles-v2\node_modules\@rushstack\worker-pool\lib\WorkerPool.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }`

Also, this is my setup:
√ SharePoint Framework v1.11.0
√ Node v10.24.1
√ yo v3.1.1
√ gulp-cli v2.3.0
√ bundled typescript used

Some insight on how to resolve would be appreciated!
(new to github so apologies if I'm not going about asking this the right way)

**Comment by omarelanis** [comment]
Hi, do you happen to have nvm installed? Can you try installing version 10.0.0 and see if it works on that version?

nvm install 10.0.0
nvm use 10.0.0

Delete the node_modules folder then run:

npm install

Let me know how you get on

**Comment by dearcaroline** [comment]
Same thing, unfortunately:( error is sliiightly different if it matters

`{ Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\REDACTED\spResources\sp-dev-fx-webparts\samples\react-tiles-v2\node_modules\@rushstack\worker-pool\lib\WorkerPool.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3) code: 'MODULE_NOT_FOUND' }`

**Comment by crismogram** [comment]
> Hi @dearcaroline @omarelanis
> 
> the devDependencies in `package.json` have a version Mismatch:
> 
> ```
>  "devDependencies": {
>    "@microsoft/sp-build-web": "1.16.1",
>    "@microsoft/sp-webpart-workbench": "1.12.1",
> ```
> 
> change these two back to 1.11 or upgrade them to 1.16 or greater

I have the same issue and this did not work for me.

**Comment by omarelanis** [comment]
> > Hi @dearcaroline @omarelanis
> > the devDependencies in `package.json` have a version Mismatch:
> > ```
> >  "devDependencies": {
> >    "@microsoft/sp-build-web": "1.16.1",
> >    "@microsoft/sp-webpart-workbench": "1.12.1",
> > ```
> >     
> >   
> > change these two back to 1.11 or upgrade them to 1.16 or greater
> 
> I have the same issue and this did not work for me.

Hi @crismogram, I'd recommend creating a new ticket as this one is closed, the and tag this tciket in the new issue you raise. Also pelase provide full details as per the template so someone from the community can help
