### ISSUE TITLE
Error while loading Modules in App.Module.ts while using Angular4 in SPFX

### ISSUE THREAD

**Issue by Rajamallareddys** [pnp/sp-dev-fx-webparts#400]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
I am using Angular4 to build spfx webpart and its working fine until i include some MatToolbarModule Module into App.Module.ts file. Once i import Module and add it to Imports it doesn't show error but once i do "gulp serve" that's when it shows me error. I also found that Lazy loading of modules is not working either.

#### Observed Behavior
[SPLoaderError.loadComponentError]:
***Failed to load component "bcccae47-6df4-4482-80e2-01aac5e3387f" (SfmoIntakeFormWebPart).
Original error: ***Failed to load entry point from component "bcccae47-6df4-4482-80e2-01aac5e3387f" (SfmoIntakeFormWebPart).
Original error: Error loading https://component-id.invalid/bcccae47-6df4-4482-80e2-01aac5e3387f_0.0.1
	Cannot find module "rxjs/operators/take"

***INNERERROR:
***Failed to load entry point from component "bcccae47-6df4-4482-80e2-01aac5e3387f" (SfmoIntakeFormWebPart).
Original error: Error loading https://component-id.invalid/bcccae47-6df4-4482-80e2-01aac5e3387f_0.0.1
	Cannot find module "rxjs/operators/take"
***CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:10183:24)
    at new SPLoaderError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:4211:28)
    at Function.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3821:21)
    at Function.ErrorBuilder.buildLoadComponentError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3743:21)
    at https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:7952:38
    at <anonymous>

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
@Rajamallareddys did you ever solve this issue?

I'll go ahead and close it as there has been no activity here for a while. If you're still experiencing this issue, feel free to open a new one.
