### ISSUE TITLE
Unable to change reference from static2.sharepointonline.com in SPFx project

### ISSUE THREAD

**Issue by jlara005** [pnp/sp-dev-fx-webparts#4453]
### Disclaimer

Yes

### Sample

https://github.com/jlara005/TestAppCustomizer

### Contributor(s)

Me

### Libraries

Node version: v8.17.0

Package version(s):
- @microsoft/sp-core-library: ~1.4.0
- @microsoft/sp-application-base: ~1.4.0
- react: 15.6.2
- @office-ui-fabric-react: ^5.135.6
- @uifabric/styling: 5.37.0

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
    Memory: 25.51 GB / 32.00 GB
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (118.0.2088.69)
    Internet Explorer: 11.0.22621.1
```

### Reproduction

https://github.com/jlara005/TestAppCustomizer

### Bug Description

I am working on a SharePoint SE on-premises SPFx application customizer project and because of security reasons there is no internet access. The fonts keep being fetched from https://static2.sharepointonline.com/files/fabric/assets.

Seems like @uifabric/styling/lib/styles/DefaultFontStyles.js is one of the main culprits having the DefaultBaseUrl set to the above link. I have tried to set the fontBaseUrl window property before all imports on the main entrypoint file TestAppCustomizerApplicationCustomizer.ts file and the reference to static2.sharepointonline.com still remains. Seems like the imports are being evaluated before the property is being set. How can I set this on an application customizer SPFx project?

Actual behavior:
- Several CSS/Font assets have to be fetched from CDN every time.
- Adding the following property to the window object before all imports on the main entrypoint file doesn't work
window.FabricConfig = {
    fontBaseUrl: 'https://mycdn.com'
};
- Network requests stay same. There is no request for own CDN.

Expected behavior:
- Setting the property will allow override to default url
- All CSS/Font dependencies should be included as part of the NPM package.

![font-trace](https://github.com/pnp/sp-dev-fx-webparts/assets/29823126/e58b81e9-9604-472e-9f3b-342d5c4fb55a)

### Steps to reproduce

1. Clone repository https://github.com/jlara005/TestAppCustomizer
2. Install node modules
3. Run "gulp serve"
4. Look at developer tools "network" tab and notice the fonts being fetched from static2.sharepointonline.com

### Expected behavior

- Setting the fontBaseUrl property will allow override to default url
- All CSS/Font dependencies should be included as part of the NPM package.

### Target SharePoint environment

SharePoint Server Subscription Edition (on-premise)

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

8.17.0

### What version of Node.js is required by the sample?

8.17.0

### Paste the results of SPFx doctor

This doesn't seem to work with the low node version:

import fs from 'fs';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by jlara005** [comment]
Anyone?
