### ISSUE TITLE
Modern Script Editor Webpart is not working

### ISSUE THREAD

**Issue by pradeemi** [pnp/sp-dev-fx-webparts#4480]
### Disclaimer

Yes

### Sample

Modern Script Editor Webpart

### Contributor(s)

http://aka.ms/m365pnp

### What happened?

"Modern Script Editor" Webparts are not working/loading properly on SharePoint Online pages. Please find the below error details and attachments and resolve this issue on high priority as this is impacting multiple users. 

Error details: Something went wrong If the problem persists, contact the site administrator and give them the information in Technical Details. TECHNICAL DETAILS

ERROR:
Script error for: 3a328f0a-99c4-4b28-95ab-fe0847f657a3_0.0.1
http://requirejs.org/docs/errors.html#scripterror
CALL STACK:
Error: Script error for: 3a328f0a-99c4-4b28-95ab-fe0847f657a3_0.0.1
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_cc09beedac12482b5e7fa1f1e86d8093.js:79:248587), <anonymous>:8:252)
at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_cc09beedac12482b5e7fa1f1e86d8093.js:79:248587), <anonymous>:30:244)

### Steps to reproduce

1. Visit any SharePoint online site.
2. Add modern script editor webpart on SharePoint page.
3. Below error gets displayed:

Error details: Something went wrong If the problem persists, contact the site administrator and give them the information in Technical Details. TECHNICAL DETAILS

ERROR:
Script error for: 3a328f0a-99c4-4b28-95ab-fe0847f657a3_0.0.1
http://requirejs.org/docs/errors.html#scripterror
CALL STACK:
Error: Script error for: 3a328f0a-99c4-4b28-95ab-fe0847f657a3_0.0.1
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_cc09beedac12482b5e7fa1f1e86d8093.js:79:248587), <anonymous>:8:252)
at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_cc09beedac12482b5e7fa1f1e86d8093.js:79:248587), <anonymous>:30:244)

### Expected behavior

Modern script editor webpart should not throw below error:

Error details: Something went wrong If the problem persists, contact the site administrator and give them the information in Technical Details. TECHNICAL DETAILS

ERROR:
Script error for: 3a328f0a-99c4-4b28-95ab-fe0847f657a3_0.0.1
http://requirejs.org/docs/errors.html#scripterror
CALL STACK:
Error: Script error for: 3a328f0a-99c4-4b28-95ab-fe0847f657a3_0.0.1
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_cc09beedac12482b5e7fa1f1e86d8093.js:79:248587), <anonymous>:8:252)
at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_cc09beedac12482b5e7fa1f1e86d8093.js:79:248587), <anonymous>:30:244)

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

Not applicable

### What version of Node.js is required by the sample?

Not applicable

### Paste the results of SPFx doctor

Error details: Something went wrong If the problem persists, contact the site administrator and give them the information in Technical Details. TECHNICAL DETAILS

ERROR:
Script error for: 3a328f0a-99c4-4b28-95ab-fe0847f657a3_0.0.1
http://requirejs.org/docs/errors.html#scripterror
CALL STACK:
Error: Script error for: 3a328f0a-99c4-4b28-95ab-fe0847f657a3_0.0.1
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_cc09beedac12482b5e7fa1f1e86d8093.js:79:248587), <anonymous>:8:252)
at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_cc09beedac12482b5e7fa1f1e86d8093.js:79:248587), <anonymous>:30:244)

**Comment by pradeemi** [comment]
Hi Team,

is there any update?

**Comment by pradeemi** [comment]
Thanks for the response, expecting at least a reason why package is not working?

**Comment by Tanddant** [comment]
@pradeemi I cannot replicate the issue, you skipped over a few steps when filling out the bug report, do you mind updating with the following?

- What version of Node.js is currently installed on your workstation?
- Paste the results of SPFx doctor
