### ISSUE TITLE
react-organization-chart - MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by rspartas** [pnp/sp-dev-fx-webparts#4501]
### Disclaimer

Yes

### Sample

react-organization-chart

### Contributor(s)

@joaojmendes

### What happened?

Keep receiving the following error message when trying to install using node v8, v10 and v18:

{ Error: Cannot find module 'node:path'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.149411 (C:\Users\user\Downloads\sp-dev-fx-webparts-main\sp-dev-fx-webparts-main\samples\react-organization-chart\node_modules\@microsoft\rush-lib\dist\rush-lib.js:461:18)
    at __webpack_require__ (C:\Users\user\Downloads\sp-dev-fx-webparts-main\sp-dev-fx-webparts-main\samples\react-organization-chart\node_modules\@microsoft\rush-lib\dist\rush-lib.js:562:41)
    at Object.74151 (C:\Users\user\Downloads\sp-dev-fx-webparts-main\sp-dev-fx-webparts-main\samples\react-organization-chart\node_modules\@microsoft\rush-lib\dist\commons.js:18203:67)
    at __webpack_require__ (C:\Users\user\Downloads\sp-dev-fx-webparts-main\sp-dev-fx-webparts-main\samples\react-organization-chart\node_modules\@microsoft\rush-lib\dist\rush-lib.js:562:41)
    at Object.62165 (C:\Users\user\Downloads\sp-dev-fx-webparts-main\sp-dev-fx-webparts-main\samples\react-organization-chart\node_modules\@microsoft\rush-lib\dist\commons.js:10485:93)
    at __webpack_require__ (C:\Users\user\Downloads\sp-dev-fx-webparts-main\sp-dev-fx-webparts-main\samples\react-organization-chart\node_modules\@microsoft\rush-lib\dist\rush-lib.js:562:41) code: 'MODULE_NOT_FOUND' }

### Steps to reproduce

1. npm install
2. npm install -g gulp
3. gulp build

### Expected behavior

Trying to create a sppkg file to upload to SharePoint

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v10.24.1

### What version of Node.js is required by the sample?

v10.24.1

### Paste the results of SPFx doctor

C:\Users\user\AppData\Roaming\npm\node_modules\@pnp\cli-microsoft365\dist\index.js:2
import { Cli } from './cli/Cli.js';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by rspartas** [comment]
I also receive an error when I use the recommended version
