### ISSUE TITLE
Node-sass v3.13.1/win32-x64-57_binding.node Not Found

### ISSUE THREAD

**Issue by JuanmCanamero** [pnp/sp-dev-fx-webparts#501]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

Hi, When I am trying do npm i, I recive this error:

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

After this error, another errors:

gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\MyUser\Documents\react-yammer-api\node_modules\which\which.js:13:12)

Anyone can help me?

Thanks.

**Comment by JuanmCanamero** [comment]
I finally can complete npm Install. but now when I try compile, I recive this errors:

[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(7959,10): error TS2300: Duplicate identifier 'Headers'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(7968,12): error TS2300: Duplicate identifier 'Headers'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(13114,10): error TS2300: Duplicate identifier 'Request'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(13131,12): error TS2300: Duplicate identifier 'Request'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(13136,10): error TS2300: Duplicate identifier 'Response'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(13147,12): error TS2300: Duplicate identifier 'Response'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(18750,17): error TS2300: Duplicate identifier 'fetch'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(18755,5): error TS2300: Duplicate identifier 'BodyInit'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(18786,5): error TS2300: Duplicate identifier 'RequestInfo'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(18835,5): error TS2300: Duplicate identifier 'RequestCache'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(18836,5): error TS2300: Duplicate identifier 'RequestCredentials'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(18838,5): error TS2300: Duplicate identifier 'RequestMode'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(18839,5): error TS2300: Duplicate identifier 'RequestRedirect'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-build-common\node_modules\typescript\lib\lib.d.ts(18841,5): error TS2300: Duplicate identifier 'ResponseType'.
[01:09:55] Error - typescript - node_modules\@microsoft\sp-http\lib\httpClient\HttpClientResponse.d.ts(16,21): error TS2420: Class 'HttpClientResponse' incorrectly implements interface 'Response'.
[01:09:55] Error - typescript - node_modules\@types\react\index.d.ts(164,10): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(5,14): error TS2300: Duplicate identifier 'Request'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(20,1): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'any', but here has type 'string[] | Headers | { [index: string]: string; }'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(36,5): error TS2300: Duplicate identifier 'RequestMode'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(37,5): error TS2300: Duplicate identifier 'RequestRedirect'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(38,5): error TS2300: Duplicate identifier 'RequestCredentials'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(39,5): error TS2300: Duplicate identifier 'RequestCache'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(47,14): error TS2300: Duplicate identifier 'Headers'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(59,1): error TS2687: All declarations of 'bodyUsed' must have identical modifiers.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(68,14): error TS2300: Duplicate identifier 'Response'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(81,5): error TS2300: Duplicate identifier 'ResponseType'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(84,1): error TS2687: All declarations of 'status' must have identical modifiers.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(86,1): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'any', but here has type 'HeaderInit'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(90,13): error TS2300: Duplicate identifier 'BodyInit'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(91,13): error TS2300: Duplicate identifier 'RequestInfo'.
[01:09:55] Error - typescript - node_modules\@types\whatwg-fetch\index.d.ts(97,12): error TS2300: Duplicate identifier 'fetch'.
[01:09:55] Error - typescript - node_modules\@uifabric\utilities\lib\Customizer.d.ts(21,54): error TS2559: Type 'ICustomizerProps' has no properties in common with type 'IBaseProps'.
[01:09:55] Error - typescript - node_modules\office-ui-fabric-react\lib\components\Button\BaseButton.d.ts(2,54): error TS2559: Type 'IButtonProps' has no properties in common with type 'IBaseProps'.
[01:09:55] Error - typescript - node_modules\office-ui-fabric-react\lib\components\Button\Button.d.ts(6,50): error TS2559: Type 'IButtonProps' has no properties in common with type 'IBaseProps'.
[01:09:55] Error - typescript - node_modules\office-ui-fabric-react\lib\components\SearchBox\SearchBox.d.ts(8,53): error TS2559: Type 'ISearchBoxProps' has no properties in common with type 'IBaseProps'.
[01:09:55] Error - 'typescript' sub task errored after 1.61 s
 TypeScript error(s) occurred.
[01:09:55] 'bundle' errored after 3.14 s

What I need?

THanks

**Comment by StfBauer** [comment]
Do you have Windows build tools installed? This seem to cause the first error.

https://www.npmjs.com/package/windows-build-tools

If you haven't please install these, delete the node_modules folder and try `npm install` again.

Just a shot in the wild.

**Comment by gord89** [comment]
I think StfBauer is right.
I had a similar mistake, helped the following:

~~~
npm install --global --production windows-build-tools
npm rebuild node-sass
~~~

**Comment by tkerkman** [comment]
StfBauer and gord89  recommendation fixed the issue for me.. thanks!

**Comment by nikokeefe** [comment]
a perfect shot in the wild!!

installed win build tools, deleted my folder, tried again and it worked

Cheers

**Comment by chicuonght** [comment]
C:\Users\chicuonght\source-code\aloland\bds>gulp
module.js:549
    throw err;
    ^

Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\chicuonght\source-code\aloland\bds\gulpfile.js:15:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by shmily0723** [comment]
> 我认为StfBauer是对的。
> 我有类似的错误，帮助了以下：
> 
> ```
> npm install --global --production windows-build-tools
> npm rebuild node-sass
> ```

nice!

**Comment by sahiba11** [comment]
Hi,
I am getting similar error on running npm install laravel-elixir. I am using laravel version 5.2,node version 10.15,python 2.7.

> C:\xampp\htdocs\udemy>npm install laravel-elixir
> npm WARN deprecated babel-preset-es2015@6.24.1: ?  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/e
> nv to update!
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated browserslist@0.4.0: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
> npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
> npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> 
> > node-sass@3.13.1 install C:\xampp\htdocs\udemy\node_modules\laravel-elixir\node_modules\node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node":
> 
> HTTP error 404 Not Found
> 
> Hint: If github.com is not accessible in your location
>       try setting a proxy via HTTP_PROXY, e.g.
> 
>       export HTTP_PROXY=http://example.com:1234
> 
> or configure npm proxy via
> 
>       npm config set proxy http://example.com:8080
> 
> > node-sass@3.13.1 postinstall C:\xampp\htdocs\udemy\node_modules\laravel-elixir\node_modules\node-sass
> > node scripts/build.js
> 
> Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\udemy\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --li
> bsass_cflags= --libsass_ldflags= --libsass_library=
> gyp info it worked if it ends with ok
> gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> gyp verb cli   'C:\\xampp\\htdocs\\udemy\\node_modules\\node-gyp\\bin\\node-gyp.js',
> gyp verb cli   'rebuild',
> gyp verb cli   '--verbose',
> gyp verb cli   '--libsass_ext=',
> gyp verb cli   '--libsass_cflags=',
> gyp verb cli   '--libsass_ldflags=',
> gyp verb cli   '--libsass_library=' ]
> gyp info using node-gyp@3.8.0
> gyp info using node@10.15.3 | win32 | x64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb check python checking for Python executable "python2.7" in the PATH
> gyp verb `which` failed Error: not found: python2.7
> gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\udemy\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (C:\xampp\htdocs\udemy\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (C:\xampp\htdocs\udemy\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at C:\xampp\htdocs\udemy\node_modules\which\which.js:89:16
> gyp verb `which` failed     at C:\xampp\htdocs\udemy\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at C:\xampp\htdocs\udemy\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
> gyp verb `which` failed  python2.7 { Error: not found: python2.7
> gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\udemy\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (C:\xampp\htdocs\udemy\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (C:\xampp\htdocs\udemy\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at C:\xampp\htdocs\udemy\node_modules\which\which.js:89:16
> gyp verb `which` failed     at C:\xampp\htdocs\udemy\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at C:\xampp\htdocs\udemy\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
> gyp verb `which` failed   stack:
> gyp verb `which` failed    'Error: not found: python2.7\n    at getNotFoundError (C:\\xampp\\htdocs\\udemy\\node_modules\\which\\which.js:13
> :12)\n    at F (C:\\xampp\\htdocs\\udemy\\node_modules\\which\\which.js:68:19)\n    at E (C:\\xampp\\htdocs\\udemy\\node_modules\\which\\whi
> ch.js:80:29)\n    at C:\\xampp\\htdocs\\udemy\\node_modules\\which\\which.js:89:16\n    at C:\\xampp\\htdocs\\udemy\\node_modules\\isexe\\in
> dex.js:42:5\n    at C:\\xampp\\htdocs\\udemy\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
> gyp verb `which` failed   code: 'ENOENT' }
> gyp verb could not find "python2.7". checking python launcher
> gyp verb could not find "python2.7". guessing location
> gyp verb ensuring that file exists: C:\Python27\python.exe
> gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.14
> gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
> gyp verb get node dir no --target version specified, falling back to host node version: 10.15.3
> gyp verb command install [ '10.15.3' ]
> gyp verb install input version string "10.15.3"
> gyp verb install installing version: 10.15.3
> gyp verb install --ensure was passed, so won't reinstall if already installed
> gyp verb install version is already installed, need to check "installVersion"
> gyp verb got "installVersion" 9
> gyp verb needs "installVersion" 9
> gyp verb install version is good
> gyp verb get node dir target node version installed: 10.15.3
> gyp verb build dir attempting to create "build" dir: C:\xampp\htdocs\udemy\node_modules\laravel-elixir\node_modules\node-sass\build
> gyp verb build dir "build" dir needed to be created? C:\xampp\htdocs\udemy\node_modules\laravel-elixir\node_modules\node-sass\build
> gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
> gyp verb find vs2017   - Found Microsoft.VisualStudio.Component.VC.Tools.x86.x64
> gyp verb find vs2017   - Found Microsoft.VisualStudio.VC.MSBuild.Base
> gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows8
> 1SDK)
> gyp verb find vs2017   - Some required components are missing, not using this installation
> gyp verb Not using VS2017: No usable installation of VS2017 found
> gyp verb build/config.gypi creating config file
> gyp verb build/config.gypi writing out config file: C:\xampp\htdocs\udemy\node_modules\laravel-elixir\node_modules\node-sass\build\config.gy
> pi
> gyp verb config.gypi checking for gypi file: C:\xampp\htdocs\udemy\node_modules\laravel-elixir\node_modules\node-sass\config.gypi
> gyp verb common.gypi checking for gypi file: C:\xampp\htdocs\udemy\node_modules\laravel-elixir\node_modules\node-sass\common.gypi
> gyp verb gyp gyp format was not specified; forcing "msvs"
> gyp info spawn C:\Python27\python.exe
> gyp info spawn args [ 'C:\\xampp\\htdocs\\udemy\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'msvs',
> gyp info spawn args   '-G',
> gyp info spawn args   'msvs_version=auto',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\xampp\\htdocs\\udemy\\node_modules\\laravel-elixir\\node_modules\\node-sass\\build\\config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\xampp\\htdocs\\udemy\\node_modules\\node-gyp\\addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Users\\Dell\\.node-gyp\\10.15.3\\include\\node\\common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Dell\\.node-gyp\\10.15.3',
> gyp info spawn args   '-Dnode_gyp_dir=C:\\xampp\\htdocs\\udemy\\node_modules\\node-gyp',
> gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Dell\\.node-gyp\\10.15.3\\<(target_arch)\\node.lib',
> gyp info spawn args   '-Dmodule_root_dir=C:\\xampp\\htdocs\\udemy\\node_modules\\laravel-elixir\\node_modules\\node-sass',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'C:\\xampp\\htdocs\\udemy\\node_modules\\laravel-elixir\\node_modules\\node-sass\\build',
> gyp info spawn args   '-Goutput_dir=.' ]
> Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
> Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
> Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
> Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
> gyp verb command build []
> gyp verb build type Release
> gyp verb architecture x64
> gyp verb node dev dir C:\Users\Dell\.node-gyp\10.15.3
> gyp verb found first Solution file build/binding.sln
> gyp verb could not find "msbuild.exe" in PATH - finding location in registry
> gyp ERR! build error
> gyp ERR! stack Error: Command failed: reg query "HKLM\Software\Microsoft\MSBuild\ToolsVersions" /s /reg:32
> gyp ERR! stack 'reg' is not recognized as an internal or external command,
> gyp ERR! stack operable program or batch file.
> gyp ERR! stack
> gyp ERR! stack Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
> gyp ERR! stack     at C:\xampp\htdocs\udemy\node_modules\node-gyp\lib\build.js:142:25
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:301:5)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\udemy\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--ver
> bose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd C:\xampp\htdocs\udemy\node_modules\laravel-elixir\node_modules\node-sass
> gyp ERR! node -v v10.15.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> Build failed with error code: 1
> npm WARN rollback Rolling back node-pre-gyp@0.10.3 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\xampp\htdoc
> s\udemy\node_modules\fsevents\node_modules'
> npm WARN rollback Rolling back node-sass@3.13.1 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\xampp\htdocs\u
> demy\node_modules\laravel-elixir\node_modules'
> npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"
> win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-sass@3.13.1 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2019-04-11T07_17_38_254Z-debug.log

**Comment by sahiba11** [comment]
As of windows build tool , i tried installing it using npm but it was getting stuck after visual studio build tools. So i tried the below steps suggested here https://github.com/felixrieseberg/windows-build-tools/issues/47#issuecomment-362130465.

> * Install VS Build Tools (http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe)
> * Install Python 2.7 (https://www.python.org/ftp/python/2.7.14/python-2.7.14.msi)
> * npm config set python python2.7
> * (If using yarn): yarn config set msvs_version 2015 --global

@StfBauer I am getting the same error as posted above on deleting the node modules folder and doing npm install again

**Comment by pmiranda-geo** [comment]
@sahiba11 same here, on Windows 7, Laravel 5.1

**Comment by hugoabernier** [comment]
Closing this issue as there has been no activity for over a year. If you run into this issue, feel free to open a new issue.

**Comment by vimplus** [comment]
从 [node-sass@4.x](https://npm.taobao.org/mirrors/node-sass/v4.6.0/win32-x64-57_binding.node) 下载 `win32-x64-57_binding.node`，指定 `sass_binary_path` 安装，如下：

```
$ npm i node-sass@3.13.1 --sass_binary_path=C:\Users\<username>\Downloads\win32-x64-57_binding.node
```
