### ISSUE TITLE
react-list-search - 

### ISSUE THREAD

**Issue by hesske** [pnp/sp-dev-fx-webparts#5118]
### Disclaimer

Yes

### Sample

react-list-search

### Contributor(s)

@albegut

### What happened?

I am running into the following error when trying to run `gulp serve` using Node 14.21.3 and $ gulp --version
CLI version: 3.0.0
Local version: 4.0.2:

> $ gulp serve
> F:\Documents\GitHub\sp-search-webparts\sp-dev-fx-webparts\samples\react-list-search\node_modules\@azure\core-lro\dist\commonjs\poller\poller.js:81
>             pollUntilDone: (pollOptions) => (resultPromise ??= (async () => {
>                                                            ^^^
> 
> SyntaxError: Unexpected token '??='
>     at compileFunction (<anonymous>)
>     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
>     at Module._compile (internal/modules/cjs/loader.js:1078:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
>     at Module.load (internal/modules/cjs/loader.js:979:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
>     at Module.require (internal/modules/cjs/loader.js:1003:19)
>     at require (internal/modules/cjs/helpers.js:107:18)
>     at Object.<anonymous> (F:\Documents\GitHub\sp-search-webparts\sp-dev-fx-webparts\samples\react-list-search\node_modules\@azure\core-lro\dist\commonjs\http\poller.js:7:21)
>     at Module._compile (internal/modules/cjs/loader.js:1114:14)

I found this error referenced in this issue for Node 14: https://github.com/Azure/azure-sdk-for-js/issues/28918
Is there a way to get this sample updated for a newer version of Node since 14 looks to be out of support? Or is there a workaround for the poller.js issue? Or, even better, is there a way to get a precompiled version of this web part?

### Steps to reproduce

1. Install Node 14.21.3
2. Install Gulp global and then local
3. Run npm install
4. Run gulp serv
5.

### Expected behavior

A web part package that I can use in Sharepoint
I'm not sure on this, but was thinking these files were what I needed:
Sppkg
Download .sppkg files from sppkg folder
Upload files to App Catalog
Approve the API permissions in the new SP admin center (only needed if you are going to enable list item modern audience)

### Target SharePoint environment

SharePoint Online

### Developer environment

None

### Browsers

- [ ] Internet Explorer
- [X] Microsoft Edge
- [X] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

14.21.3

### What version of Node.js is required by the sample?

14

### Paste the results of SPFx doctor

Unable to run spfx doctor. Below is the error received trying to run it or using `m365 version` to get the version:

> file:///C:/Users/hesske/AppData/Roaming/npm/node_modules/@pnp/cli-microsoft365/node_modules/ora/node_modules/string-width/index.js:5
const segmenter = new Intl.Segmenter();
                  ^

TypeError: Intl.Segmenter is not a constructor
    at file:///C:/Users/hesske/AppData/Roaming/npm/node_modules/@pnp/cli-microsoft365/node_modules/ora/node_modules/string-width/index.js:5:19
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)

**Comment by hesske** [comment]
I ended up just running this in Docker as recommended and the issue no longer occurred.
