### ISSUE TITLE
react-script-editor:  Your dev environment is running NodeJS version v20.10.0 which does not meet the requirements for running this tool.

### ISSUE THREAD

**Issue by oshihirii** [pnp/sp-dev-fx-webparts#5163]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor

### Contributor(s)

@wobba

### What happened?

When I run `gulp serve` I get this error:

```
$ npx gulp serve
Error: Your dev environment is running NodeJS version v20.10.0 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=12.13.0 <13.0.0 || >=14.15.0 <15.0.0 || >=16.13.0 <17.0.0 || >=18.17.1 <19.0.0
    at SPWebBuildRig.initialize (C:\My_Repos\sp-dev-fx-webparts\samples\react-script-editor\node_modules\@microsoft\sp-build-web\lib\SPBuildRig.js:50:19)
    at Object.initialize (C:\My_Repos\sp-dev-fx-webparts\samples\react-script-editor\node_modules\@microsoft\sp-build-web\lib\index.js:35:17)
    at Object.<anonymous> (C:\My_Repos\sp-dev-fx-webparts\samples\react-script-editor\gulpfile.js:34:7)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at requireOrImport (C:\My_Repos\sp-dev-fx-webparts\samples\react-script-editor\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11)
```

### Steps to reproduce

1.  Go to:  https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor
2.  Go to:  https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-script-editor#minimal-path-to-awesome
3.  Run the following:

```
git clone https://github.com/pnp/sp-dev-fx-webparts.git

cd sp-dev-fx-webparts/samples/react-script-editor

npm install

npx gulp serve
```

### Expected behavior

I expected the install process to work as described.  

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v20.10.0

### What version of Node.js is required by the sample?

It doesnt say

### Paste the results of SPFx doctor

I dont know what this means, i don't use SPFx or react or typescript - I just want to add a script editor web part to a SharePoint Online page.

**Comment by wobba** [comment]
As per .yo-rc.json the code is built using SPFx v1.18.2, and if you check https://learn.microsoft.com/en-us/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility you see you need node v16 or v18 to build.
