### ISSUE TITLE
Error whan installing react-search

### ISSUE THREAD

**Issue by shaysil** [pnp/sp-dev-fx-webparts#711]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Observed Behavior
after running npm i / npm install getting an error msg(i;m using npm V6.4.1):

gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\SPDEV\New folder\react-search\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\SPDEV\New folder\react-search\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at E:\SPDEV\New folder\react-search\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\SPDEV\\New folder\\react-search\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\SPDEV\New folder\react-search\node_modules\node-sass
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Steps to Reproduce

npm i 

## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by hugoabernier** [comment]
@shaysil did you ever resolve this issue?

Since you created this issue, the Office 365 CLI team has create a command [spfx doctor](https://pnp.github.io/office365-cli/cmd/spfx/doctor/) designed to help identify if there are issues with your installation or project.

I'll go ahead and close this issue as there has been no activity here for a while, but if you're still having problems, try `spfx doctor` and feel free to open a new issue.
