### ISSUE TITLE
[SPLoaderError.loadComponentError]: error when dropping webpart on a modern page

### ISSUE THREAD

**Issue by bgournay** [pnp/sp-dev-fx-webparts#772]
## Category

- [ ] Question
- [X] Bug
- [ ] Enhancement

## Expected or Desired Behavior

The webpart was working fine and one day it stopped working. I keep having that error:

_Désolé... Nous avons rencontré un problème
Si le problème persiste, contactez l’administrateur du site et communiquez-lui les informations figurant dans la section Détails techniques.
DÉTAILS TECHNIQUES
[SPLoaderError.loadComponentError]:
***Failed to load component "ac515af1-4490-4c7b-8191-d49b41b26c5e" (ContentQueryWebPart).
Original error: ***Failed to load entry point from component "ac515af1-4490-4c7b-8191-d49b41b26c5e" (ContentQueryWebPart).
Original error: Error loading https://component-id.invalid/ac515af1-4490-4c7b-8191-d49b41b26c5e_1.0.11
	https://component-id.invalid/ac515af1-4490-4c7b-8191-d49b41b26c5e_1.0.11 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.

ERREUR INTERNE :
***Failed to load entry point from component "ac515af1-4490-4c7b-8191-d49b41b26c5e" (ContentQueryWebPart).
Original error: Error loading https://component-id.invalid/ac515af1-4490-4c7b-8191-d49b41b26c5e_1.0.11
	https://component-id.invalid/ac515af1-4490-4c7b-8191-d49b41b26c5e_1.0.11 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.
PILE D’APPELS :
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-01-18.008/sp-pages-assembly_fr-fr_65d5ac47ae69b0fcc460353fa37c2ef2.js:867:16049)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-01-18.008/sp-pages-assembly_fr-fr_65d5ac47ae69b0fcc460353fa37c2ef2.js:1770:21052)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-01-18.008/sp-pages-assembly_fr-fr_65d5ac47ae69b0fcc460353fa37c2ef2.js:1770:16214)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-01-18.008/sp-pages-assembly_fr-fr_65d5ac47ae69b0fcc460353fa37c2ef2.js:1770:12245)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-01-18.008/sp-pages-assembly_fr-fr_65d5ac47ae69b0fcc460353fa37c2ef2.js:1770:59501_

## Steps to Reproduce

the error happens when i add a webpart on a modern page

**Comment by hugoabernier** [comment]
@bgournay did you ever resolve this issue?

I'll go ahead and close it as there has been no activity here got a while, and this issue list is intended for issues related to web part samples. 

If you still have issues, feel free to open a new issue in the sp-dev-docs repository.
