### ISSUE TITLE
react-aggregated-calendar issue when live on site.

### ISSUE THREAD

**Issue by Loevbo** [pnp/sp-dev-fx-webparts#811]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors

@dhavalshah01 

## Expected or Desired Behavior

The problem is that everything is working fine until i get deployed to the SharePoint site and goes live. When it's in workbench mode the calendar works just file.

## Observed Behavior

Here is the error message displayed in the webpart:

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "be293fec-29f2-4db2-869a-604e560980fa" (ReactAggregatedCalendarWebPart).
Original error: ***Failed to load URL 'https://sharepointarena.sharepoint.com/sites/SPFX/CDN/react-aggregated-calendar/react-aggregated-calendar-sp-client-custom-fields_strings_en-us_517cbd7b26367d7a6cbe94ede5a0f7b8.js' for resource 'sp-client-custom-fields/strings' in component 'be293fec-29f2-4db2-869a-604e560980fa' (ReactAggregatedCalendarWebPart). There was a network problem.

***INNERERROR:
***Failed to load URL 'https://sharepointarena.sharepoint.com/sites/SPFX/CDN/react-aggregated-calendar/react-aggregated-calendar-sp-client-custom-fields_strings_en-us_517cbd7b26367d7a6cbe94ede5a0f7b8.js' for resource 'sp-client-custom-fields/strings' in component 'be293fec-29f2-4db2-869a-604e560980fa' (ReactAggregatedCalendarWebPart). There was a network problem.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-08.005/sp-pages-assembly_en-us_9073a17c253d35d63f2a55dfb274f298.js:889:16049)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-08.005/sp-pages-assembly_en-us_9073a17c253d35d63f2a55dfb274f298.js:1512:21125)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-08.005/sp-pages-assembly_en-us_9073a17c253d35d63f2a55dfb274f298.js:1512:16214)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-08.005/sp-pages-assembly_en-us_9073a17c253d35d63f2a55dfb274f298.js:1512:12245)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-03-08.005/sp-pages-assembly_en-us_9073a17c253d35d63f2a55dfb274f298.js:1512:60369

Do anyone know how to fix this problem.

**Comment by hanaRose** [comment]
@Loevbo  did you figure this out?
I'm encountering the same issue

**Comment by Loevbo** [comment]
@hanaRose Nope, I was hoping that some authors would replay back.

**Comment by hanaRose** [comment]
@Loevbo I have a feeling it has to do with the fact that my site isn't in English, is yours an English site?

**Comment by harrychen1** [comment]
Anyone has any update on this? I've seen the same issue and the code seems to look at cdn below
"cdnBasePath": "https://sharepointarena.sharepoint.com/sites/SPFX/CDN/react-aggregated-calendar"

However, it's mot available.

When you deploy the package, it also indicate the code will get content from https://spclientsideassetlibrary.: https://cdnjs.cloudflare.com; https://code.jquery.com

All of these also need to be available.

Will take a look if I can fix the issue. Please let us know if you have solution.

**Comment by Suresh-Lakum** [comment]
Any update on same? I am facing same issue.

**Comment by harrychen1** [comment]
Could any author would replay back on this issue? Thanks.

**Comment by hugoabernier** [comment]
Hey @harrychen1 , @Suresh-Lakum  I just noticed that you reported this issue. Are you still experiencing problems?

**Comment by harrychen1** [comment]
Yes.

Thanks.

**Comment by hugoabernier** [comment]
@Loevbo did you ever resolve this issue?

I'll go ahead and close it as there has been no recent activity for a while. If you're still experiencing this issue, feel free to open a new issue and -- hopefully -- someone will notice this issue and will be able to help you.

**Comment by matteomessmer** [comment]
Hi, I'm facing this same issue, has it ever been resolved?

**Comment by jevgenij-martynenko** [comment]
Same issue here. Any workarounds?

**Comment by matteomessmer** [comment]
Hi, I solved using Syncfusion scheduler, it has a community license

**Comment by ankitsaxena86** [comment]
I am also facing this same issue. Have any one managed to work around this?

**Comment by matteomessmer** [comment]
Hi @ankitsaxena86, I did solve this
I'm currently checking the changes I did, first thing I found is that I changed the $schema property in config/copy-assets.json 
 
"$schema": "https://developer.microsoft.com/json-schemas/spfx-build/copy-assets.schema.json"

Another thing I changed is config/write-manifest.json

{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/write-manifests.schema.json",
  "cdnBasePath": ""
}

Try with these changes, I'm not 100% sure this is the complete solution
I will be back at this if you still need help later this week!
