### ISSUE TITLE
react-calendar-feed is not working in IE

### ISSUE THREAD

**Issue by Rajrup-net** [pnp/sp-dev-fx-webparts#978]
react-calendar-feed is not working in IE.. Its throwing below error:

**Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
Technical Details

[SPLoaderError.loadComponentError]:
***Failed to load component "acef6c3f-852a-42e3-8a4b-7ea191ae9687" (CalendarFeedSummaryWebPart). Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/thebma.sharepoint.com/sites/appcatalog/ClientSideAssets/25653136-fc83-4abe-b9d2-a4ac041959d5/calendar-feed-summary-web-part_a5b64268e503b3b539ba832ffc06d63c.js' for resource 'calendar-feed-summary-web-part' in component 'acef6c3f-852a-42e3-8a4b-7ea191ae9687' (CalendarFeedSummaryWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://publiccdn.sharepointonline.com/thebma.sharepoint.com/sites/appcatalog/ClientSideAssets/25653136-fc83-4abe-b9d2-a4ac041959d5/calendar-feed-summary-web-part_a5b64268e503b3b539ba832ffc06d63c.js' for resource 'calendar-feed-summary-web-part' in component 'acef6c3f-852a-42e3-8a4b-7ea191ae9687' (CalendarFeedSummaryWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
Error
   at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-08-16.010/sp-pages-assembly_en-us_89a71a07c8bdf9672544574aa95d0170.js:4:53720)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-08-16.010/sp-pages-assembly_en-us_89a71a07c8bdf9672544574aa95d0170.js:4:53256)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-08-16.010/sp-pages-assembly_en-us_89a71a07c8bdf9672544574aa95d0170.js:20:79630)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-08-16.010/sp-pages-assembly_en-us_89a71a07c8bdf9672544574aa95d0170.js:20:118295)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-08-16.010/sp-pages-assembly_en-us_89a71a07c8bdf9672544574aa95d0170.js:20:114320)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-08-16.010/sp-pages-assembly_en-us_89a71a07c8bdf9672544574aa95d0170.js:20:109769)
   at Anonymous function (https://publiccdn.sharepointonline.com/thebma.sharepoint.com/sites/appcatalog/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_c3e174542874f8fbf02e0e130b9923fa.js:51:69494)
   at Anonymous function (https://publiccdn.sharepointonline.com/thebma.sharepoint.com/sites/appcatalog/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_c3e174542874f8fbf02e0e130b9923fa.js:51:69364)
   at c (https://publiccdn.sharepointonline.com/thebma.sharepoint.com/sites/appcatalog/ClientSideAssets/890affef-33e0-4d72-bd72-36399e02143b/search-results-web-part_c3e174542874f8fbf02e0e130b9923fa.js:51:88251)**

**Comment by Rajrup-net** [comment]
Hi @hugoabernier, Can you please look into it or Can you suggest any solution ??

**Comment by hugoabernier** [comment]
Hey @Rajrup-net  thanks for reporting this issue. I'll take a look into it as soon as possible.

Next time you create an issue, I'd recommend that you take the time to fill the provided issue template as it helps automatically notify the authors of the sample in question (in this case, me!) and -- hopefully -- helps getting a resolution faster.

**Comment by hugoabernier** [comment]
@Rajrup-net the libraries that we used in this solution are not IE-compatible. 

I realize that there are still many organizations that use IE, but -- unfortunately -- many third-party libraries have given up on providing support for it. The only way to solve this issue would be to re-write the libraries from scratch to provide IE support -- something that I'm not going to be able to do within any reasonable amount of time.

Please note that we accept pull requests in this repository. If you came up with a fix to this issue, you can absolutely share your solution here.
